athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcSplitQueryBuilder.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/mysql/MySqlQueryStringBuilder.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlMetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlQueryStringBuilder.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/splits/IntegerSplitter.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/splits/SplitInfo.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/splits/SplitRange.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/splits/Splitter.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/splits/SplitterFactory.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/splits/IntegerSplitterTest.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/splits/SplitterFactoryTest.java
Adds a custom split generation logic based on table primary key. Creates basic equal ranges to generate expected number of splits. This logic works best when data is not skewed. 
This is a first version so has some limitations:
1. Number of splits is static, will be taken as input later.
2. Supports Integer splitter only. Can be expanded later to other data types.
3. Does not work for composite primary keys.
=> Add custom range split generation logic based on primary key of table.

athena-jdbc/README.md
https://github.com/awslabs/aws-athena-query-federation/issues/72
Fix JDBC README: Timestamp is currently not supported.
=> Fix JDBC README: Timestamp is currently not supported.

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/MultiplexingJdbcMetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/MultiplexingJdbcRecordHandler.java
JDBC: Better error messaging for Catalog not supported in mux.
=> JDBC: Better error messaging for Catalog not supported in mux.

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/TestBase.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java
**Issue #, if available:** https://github.com/awslabs/aws-athena-query-federation/issues/75
**Description of changes:** This change handles empty Maps that DDB allows but Athena does not.  We fallback to VARCHAR whenever we cannot infer the element types of the complex DDB Map and List types.  Also added warning logs to let the customer know this is happening and that they can use Glue to to better specify the types.
**Testing**: Unit tests and empirical testing with various DDB tables and Athena and Lambda.  The VARCHAR fallback works well and is probably better than hiding the data.  Also sanity checked the few SDK changes with the CW-Metrics connector.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> Handle empty Maps in DynamoDB Connector

athena-dynamodb/README.md, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/constants/DynamoDBConstants.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandlerTest.java
*Issue #, if available:* https://github.com/awslabs/aws-athena-query-federation/issues/78
*Description of changes:* Adding source table name and column name mapping for Glue handlers.  Data sources such as DynamoDB allow more characters and upper case in table names while Glue does not, meaning that it may not be possible for customers to make a Glue table with the same exact name
as their data source's table.  This allows customers to add a table property in Glue with the source table name.  This can also extract the source table name from an ARN populated in the Glue table's 
StorageDescriptor.Location property (Glue crawlers populate this).  It also enables a table property for column mapping.
I adapted the Dynamo connector to use this.  The other connectors expose table names directly …
=> Adding source table name and column name mapping for Glue handlers

README.md
In previous version, the README.md in root directory shows;
```
6. Run a query "show databses in `lambda:<func_name>`" where <func_name> is the name of the Lambda function you deployed in the previous steps.
```
Just fixing this typo (`show databses`) to "show databases in `lambda:<func_name>`".
=> Fixing "show database" query part

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/SchemaUtils.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandlerTest.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandlerTest.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/SchemaUtilsTest.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/TypeUtilsTest.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/UnsupportedType.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/SupportedTypes.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/MetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandlerTest.java
Fixing Issue #72 - Tables with even 1 unsupported columns are unqueriable
*Issue #, if available:* #72
- Add explicit validation to all connectors to ensure we don't accidentally return unsupported Types. This should surface this issue earlier in connector development for future mismatches.
- If an unsupported type is encountered for the JDBC connector it will be ignored and we will log an error.
- It also seems the docdb connector is vulnerable to the same issue so I'll include fixing that in this PR as well.
- Updated unit tests to ensure unsupported columns are not returned
=> Fixing Issue #72 - Tables with even 1 unsupported columns are unqueriable

athena-aws-cmdb/athena-aws-cmdb.yaml, athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml, athena-cloudwatch/athena-cloudwatch.yaml, athena-docdb/athena-docdb.yaml, athena-dynamodb/athena-dynamodb.yaml, athena-example/athena-example.yaml, athena-federation-sdk/athena-federation-sdk.yaml, athena-hbase/athena-hbase.yaml, athena-jdbc/athena-jdbc.yaml, athena-redis/athena-redis.yaml, athena-tpcds/athena-tpcds.yaml, athena-udfs/athena-udfs.yaml
Closes #73 
This change standardizes the descriptions, allowed patterns, and default values for SAR parameters across all of the connectors in this repository. When this is merged, SAR will not allow users to create invalid Lambda function names (also able to be referenced in Athena as the catalog using the format "lambda:<function-name>"), exposing an informative error message when the function name does not match the required pattern.
=> Standardizing SAR parameter configuration across connectors and adding Lambda function name validation.

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/TestBase.java
https://github.com/awslabs/aws-athena-query-federation/issues/118
Currently, If the customer did not register their DDB table with glue, we then peek n rows from the DDB table to infer the table schema. This causes an issue when we come across Struct type, as it can be free formed and we are unable to infer the correct schema. However due to the free-form-ness, we are unable to infer a perfect/correct schema. 
Long term fix is to support map type. However in the short term, we need to address the problem where the query fails if one of the nested fields in the Struct contains NULL type (of value true).
*Testing:*
Created ddb table with nested type with NULLtype (of value true) without registering the table in glue
By submitting this pull …
=> Improving DDB schema inference if the table is not registered in glue

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/SchemaBuilder.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/mysql/MySqlRecordHandlerTest.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlRecordHandlerTest.java
*Issue #, if available:* #140 
Changed fields from HashMap to LinkedHashMap. The latter will maintain the order of the elements inserted and will present a consistent schema view.
Consequently, had to change two tests in the jdbc connector to conform to new SchemaBuider.
=> Fix BUG (Issue #140) with SchemaBuilder

athena-federation-sdk/pom.xml, athena-udfs/pom.xml
*Issue #, if available:* #191 
Updating Guava dependency due to CVE-2018-10237
=> Updating Guava dependency due to CVE-2018-10237

athena-elasticsearch/README.md, athena-elasticsearch/athena-elasticsearch.yaml, athena-elasticsearch/pom.xml, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/AwsRestHighLevelClient.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/AwsRestHighLevelClientFactory.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/CacheableAwsRestHighLevelClient.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchMetadataHandler.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchRecordHandler.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/CacheableAwsRestHighLevelClientTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchDomainMapProviderTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchFieldResolverTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchGlueTypeMapperTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchMetadataHandlerTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchQueryUtilsTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchRecordHandlerTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchSchemaUtilsTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchTypeUtilsTest.java, athena-elasticsearch/src/test/resources/mockito-extensions/README.md, athena-elasticsearch/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
#180 #77 
1. Added support for parallel scans.
1. Added a client cache for client reusability.
1. Upgraded the testing platform.
=> Elasticsearch parallel scan support

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java
*Description of changes:* If user has an empty List we were trying to infer the element type using reflection, but due to type erasure that would never work, so removed it and added fallback to string/varchar.
=> Remove reflection code that doesn't work in DDB type inference

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DDBPredicateUtilsTest.java
**Issue #, if available:** N/A
This fixes an exception caused by dashes or other special characters in the alias column's name:  
`com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#fle-status" (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException;`
**Fix**: Convert illegal characters in the attribute aliases (any character or combination of characters that are NOT included in [a-zA-Z_0-9]) to underscore. 
**Example**: ```"column-$1`~!@#$%^&*()-=+[]{}\\|;:'\",.<>/?f3"``` -> ```"#column_1_f3"```
=> Alias column name normalization for DynamoDB

athena-example/LICENSE.txt
It's not clear if this subdir should actually be under MIT-0 but there are license headers in some of the files that specify Apache-2.0. If they should be MIT-0, let's do that instead.
=> Replace bogus license

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java
**Issue #, if available:** #184 (and possibly #100)
Added supplemental Glue metadata definition support for ARRAY<STRUCT<...>> and ARRAY<ARRAY<...>> including any nested permutations of the latter and former. Added unit tests.
=> Supplemental Glue metadata definition support for ARRAY<STRUCT<...>> (#184)

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java
**Issue #, if available:** #231
**Description of changes:** Added support for supplemental Glue metadata when parsing a field defined as a STRUCT containing multiple arrays attributes (e.g. `STRUCT<actors:ARRAY<STRING>,genre:ARRAY<STRING>>`).
=> [#231] Glue lex support for multi-array struct STRUCT<ARRAY<>, ARRAY<>>.

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/QueryUtils.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/Block.java
*Description of changes:* Customer raised support case indicating that queries that filter on multiple hash key values resulted in duplicate and missing rows returned.  Turns out that we were using the same split property map for every split, resulting effectively in duplicate splits.  This change creates a new split property map for each split.
Also includes two minor changes:
1. fixed issue where DocDB connector predicate builder wasn't incrementing the FieldReader position when building the value list, resulting in duplicate/missing values
2. Fixed issue where Block's toString was mutating FieldReaders' positions without resetting them (resulted in bizarre/confusing behavior during debugging)
*Testing:* unit tests and uploaded Lambda testing through Athena …
=> Fixing duplicate splits issue in DDB connector

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/QueryStatusChecker.java
*Description of changes:* See some query failures due to `Rate exceeded (Service: AmazonAthena; Status Code: 400; Error Code: ThrottlingException)`, so catching all Exceptions instead of just RuntimeException, since I can't think of a reason why we would want to throw any Athena exceptions all the way up.
=> Catching all Athena exceptions in QueryStatusChecker

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchFieldResolver.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchQueryUtils.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchQueryUtilsTest.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchRecordHandlerTest.java
*Issue #, if available:* #254, #255 
1. Nullable fields - Ignores fields/columns that do not exist in the DB record (fixed for `Elasticsearch` and `DynamoDB`). Closes #254 
2. Ranging - uses the TO operator in combination with [] for inclusive range and {} for exclusive range. Inclusive ranges are specified with square brackets [min TO max] and exclusive ranges with curly brackets {min TO max} - see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html. Closes #255 
=> Fixes nullable fields and ranging issues for Elasticsearch connector.

athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchMetadataHandler.java
*Issue #, if available: N/A
Ignore all system indices starting with period `.` (e.g. .kibana, .tasks, etc...)
=> Ignore all system indices starting with period for Elasticsearch connector

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBRecordMetadata.java
Fixes the following exception when a date column defined as `String` in a DynamoDB table is defined as `date` in the Glue metadata definitions:
``` 
2020-10-14 21:24:26 c8827898-8436-4fd4-b697-7bc4f798a998 INFO  DDBTypeUtils:239 - Date format not in cache for column LastUpdatedDate. Trying to infer format...
2020-10-14 21:24:26 c8827898-8436-4fd4-b697-7bc4f798a998 INFO  DateTimeFormatterUtil:186 - Inferred format yyyy-MM-dd for value 2020-09-08
2020-10-14 21:24:26 c8827898-8436-4fd4-b697-7bc4f798a998 INFO  DDBTypeUtils:242 - Adding datetime format yyyy-MM-dd for column LastUpdatedDate to cache
Error while processing field data: java.lang.RuntimeException
java.lang.RuntimeException: Error while processing field data
at …
```
=> Fixes UnsupportedOperationException when inferring Glue date column format for DynamoDB connector.

athena-elasticsearch/README.md, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchQueryUtils.java
Fixes the following exception when the predicate is column = timestamp (e.g.: select * from mytable where mydate = timestamp '2000-11-11 06:57:44.123'). The resulting push-down predicate when is using the `=` operator on a timestamp, needs to wrapp the timestamp in quotes, e.g.: mydate:("2000-11-11T06:57:44.123")
```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[task/:?]
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[task/:?]
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[task/:?] …
```
=> Fixes ElasticsearchStatusException when predicate is timestamp for Elasticsearch connector

tools/publish.sh
*Description of changes:* Fixes a small typo (`AS REGION` -> `AWS REGION`) in usage message.
=> Fix typo in help message

athena-aws-cmdb/src/main/resources/log4j2.xml, athena-cloudwatch-metrics/src/main/resources/log4j2.xml, athena-cloudwatch/src/main/resources/log4j2.xml, athena-docdb/src/main/resources/log4j2.xml, athena-dynamodb/src/main/resources/log4j2.xml, athena-elasticsearch/src/main/resources/log4j2.xml, athena-example/src/main/resources/log4j2.xml, athena-federation-sdk-tools/src/main/resources/log4j2.xml, athena-federation-sdk/src/test/resources/log4j2-test.xml, athena-hbase/src/main/resources/log4j2.xml, athena-jdbc/src/main/resources/log4j2.xml, athena-neptune/src/main/resources/log4j2.xml, athena-redis/src/main/resources/log4j2.xml, athena-timestream/src/main/resources/log4j2.xml, athena-tpcds/src/main/resources/log4j2.xml, athena-udfs/src/main/resources/log4j2.xml
This is a suggestion on providing more control over logging. In its current state, the athena-federation-sdk uses log level `INFO` to log full requests e.g.
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/MetadataHandler.java#L232
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/RecordHandler.java#L154
This includes potentially sensitive information if stored within Split metadata or records written back to Athena after `READ_RECORDS`. It can also be incredibly verbose if there is a lot of data being processed. While this defaults to `INFO`, an env variable can be …
=> env variable log level for athena-federation-sdk

athena-dynamodb/pom.xml, athena-federation-sdk-tools/pom.xml, athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/README.md, pom.xml
Removed awscdk:core dependency from main pom.xml which pulled in a conflicting version of the fasterxml-jackson artifacts. Added fasterxml:jackson-annotations artifact as runtime dependency for the dynamodb connector to complement version of other fasterxml-jackson artifacts pulled in by awscdk (needed for integ-tests).
=> Fixes fasterxml.jackson-annotations dependency.

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcArrowTypeConverter.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcArrowTypeConverterTest.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandlerTest.java
Cx is using Athena to query Redshift DB tables containing timestamp columns. The latter do not show up in Athena in either the table's schema or in the results of the select statements.
Converted JDBC Timestamp to Arrow DATEMILLI type.
=> Fixes JDBC Timestamp not showing up in results - JDBC Redshift connectors.

athena-elasticsearch/pom.xml, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/AwsElasticsearchFactory.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchDomainMapProvider.java, athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchMetadataHandler.java, athena-elasticsearch/src/test/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchDomainMapProviderTest.java
When using Amazon Elasticsearch service as a data-source provider, if the account being used has more than 5 Domain Names defined in Amazon Elasticsearch service, the following error will be observed in Athena for `ListDatabases`/`show databases` requests:
```
java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Unable to create domain map: Please provide a maximum of 5 Elasticsearch domain names to describe. (Service: AWSElasticsearch; Status Code: 400;...
```
Since the `DescribeElasticsearchDomains` Elasticsearch API can only process 5 domain names in a single call, the lambda function was modified to generate multiple calls to that API when the list of domain names exceeds 5.
By submitting this …
=> Fixes LambdaFunctionException: Unable to create domain map - Elasticsearch connector

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlCompositeHandler.java
Removed unused constructor parameters to allow to use this class as AWS Lambda handler directly.
=> Allow PostGreSqlCompositeHandler to be used as Lambda handler class

athena-jdbc/README.md, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcArrowTypeConverter.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcRecordHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcArrowTypeConverterTest.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandlerTest.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlMetadataHandlerTest.java
Closes #186 
Add support for ARRAY type to the PostGreSQL connector and made all unsupported types default to Varchar to support types such as UUID, etc...
=> Added support for ARRAY type - PostGreSQL JDBC connector

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/mysql/MySqlMetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlMetadataHandler.java
This MR addresses duplicate splits bug in the current implementation for athena-jdbc connectors.  I believe that the issue here is that when the number of splits is too large, the continuation token encoded should be next **unprocessed** partition.  Otherwise, the each partition at the partition boundary (MAX_SPLIT_PER_REQUEST) gets included twice in the current implementation.  One time when the MAX_SPLIT_PER_REQUEST is reached, and another time when the next request resumes from the partition that was just processed.
=> [Bug-Fix]: Duplicate splits generated when splits are continued

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcRecordHandler.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcSplitQueryBuilder.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlRecordHandlerTest.java
Closes #330.
Queries using the `date()` function in the predicate (e.g. `where mycolumn = date('2021-1-1')`) generate an exception (see below) due to invalid processing of the DATEDAY data type during predicate building. This PR fixes that issue, as well as, the extraction from the DB record that was giving incorrect results.
```
java.lang.Integer cannot be cast to org.joda.time.LocalDateTime: java.lang.ClassCastException
java.lang.ClassCastException: java.lang.Integer cannot be cast to org.joda.time.LocalDateTime
at com.amazonaws.connectors.athena.jdbc.manager.JdbcSplitQueryBuilder.buildSql(JdbcSplitQueryBuilder.java:151)
at com.amazonaws.connectors.athena.jdbc.postgresql.PostGreSqlRecordHandler.buildSplitSql(PostGreSqlRecordHandler.j …
```
=> [Fixes] ClassCastException with DATEDAY processing - PostGreSQL connector

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/model/DynamoDBIndex.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/model/DynamoDBTable.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DDBPredicateUtilsTest.java
*Issue #, if available: #279
*Description of changes: adding validation to check if projected attributes of an index contails all required attributes of a query when choosing index in AthenaDynamoDBConnector. Fix to issue#279
=> Considering attribute projection when choosing index for AthenaDynamoDBConnector.

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcSplitQueryBuilder.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlRecordHandlerTest.java
Bug fixing: athena-jdbc throws ClassCastException when handling filter on decimal type column
=> Fixing ClassCastException for decimal type in athena-jdbc connector

.github/workflows/publish_to_maven_central.yml, athena-federation-sdk/pom.xml, pom.xml
This adds a git action to publish the Federation SDK to Maven Central for new releases. 
Some additional metadata and plugins had to be added to satisfy the requirements. https://central.sonatype.org/publish/publish-maven/.
All artifacts published to the central repository need to be signed with [PGP](https://central.sonatype.org/publish/requirements/gpg/), which the `maven-gpg-plugin` handles. The private key will be uploaded to github as a [encrypted secret](https://docs.github.com/en/actions/reference/encrypted-secrets) that can then be referenced in the workflow.
=> Publish Federation SDK to Maven Central

.github/workflows/publish_to_maven_central.yml
The github action failed to upload the federation sdk to maven-central with the error
`Error: The process '/usr/bin/gpg' failed with exit code 2`. https://github.com/awslabs/aws-athena-query-federation/runs/2461556378?check_suite_focus=true 
From what I've read this looks like to be a permission issue, with gpg not having access to the necessary directory to import the key.  This is currently running on a self-hosted runner.  I tested using a hosted ubuntu runner and its working fine.  We're currently using the same ubuntu-latest runner in [another action](https://github.com/awslabs/aws-athena-query-federation/blob/master/.github/workflows/codeql-analysis.yml#L12).
For more info, you can read about the GPG key and runners …
=> Update maven central action

athena-docdb/athena-docdb.yaml, athena-elasticsearch/athena-elasticsearch.yaml, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandlerTest.java, athena-hbase/athena-hbase.yaml, athena-jdbc/athena-jdbc.yaml, athena-neptune/athena-neptune.yaml, athena-redis/athena-redis.yaml, athena-udfs/athena-udfs.yaml, athena-vertica/athena-vertica.yaml, tools/publish.sh
V2 is now available in the china and govcloud partitions.  The CloudFormation templates and GlueMetadataHandler hardcoded the arn prefix  as `aws`  which was causing deployments to fail in those partitions.  
This updates the CloudFormation templates to use the parameter [AWS::Partition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition).
I also updated the `TABLE_ARN_REGEX`  in `GlueMetadataHandler` and the publish script.
I tested the publish script and confirmed the JDBC connector was able to be deployed in cn-north-1.  
=> Remove hardcoded partitions

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/connection/DatabaseConnectionConfigBuilder.java, athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/connection/GenericJdbcConnectionFactory.java, athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/connection/DatabaseConnectionConfigBuilderTest.java
GetSecretValueRequest do support using ARN as secret id, but currently the secret pattern used to extract secret name can't accept ARN format name, such as `${arn:aws:secretsmanager:us-east-1:1234567890:secret:redshift/user/secret}`.
This commit updated the secret pattern string to support ARN format.
=> support ARN format in secret pattern

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/SchemaUtils.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/Block.java
Fixing #397 and #429 by removing deprecated maxScan(...) func call in docdb connector and marking Block constructor as public
- #397 
- #429 
- removing depricated mongodb client function call
- making Block constructor public to allow for easier integration with sources that already speak Apache Arrow
=> Fixing #397 and #429 by removing deprecated maxScan(...)

athena-timestream/src/main/java/com/amazonaws/connectors/timestream/TimestreamRecordHandler.java, athena-timestream/src/test/java/com/amazonaws/connectors/timestream/TimestreamRecordHandlerTest.java
Pagination token is not handled properly in athena-timestream connector which leads to empty query result when the dataset is large. See issue-410
1. Continue the query as long as the pagination token is returned even though the result is empty. TimeStream returns empty result with a pagination token when the query takes a longer time to finish  
2. Pass the query string even the pagination token is supplied because this is required per query API documentation: https://docs.aws.amazon.com/timestream/latest/developerguide/API_query_Query.html#timestream-query_Query-request-QueryString
*Test*
I …
=> [Issue-410] Continue query when the nextToken is returned

athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/TPCDSRecordHandler.java, athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/TPCDSUtils.java, athena-tpcds/src/test/java/com/amazonaws/athena/connectors/tpcds/TPCDSRecordHandlerTest.java
*Issue #, if available:* no opened issues
When running query for `dbgen_version` , the query fails with `java.lang.NumberFormatException`. The following output is one of the examples.
```
// Query: SELECT * FROM "athena_tpcds"."tpcds1"."dbgen_version"
Your query has the following error(s):
GENERIC_USER_ERROR: Encountered an exception[java.lang.NumberFormatException] from your LambdaFunction[arn:aws:lambda:us-east-1:885940531297:function:athena_tpcds] executed in context[S3SpillLocation{bucket='garbage-collection', key='athena-spill/ddbca176-e99f-4ddf-a5df-4f85d9af9783/900f3a8f-cf70-4919-8ee0-96483d950ab8', directory=true}] with message[For input string: "08:46:37"]
```
* Before: TPCDS `TIME` type is converted to `BigInt`. (This conversion fails and throws …
=> Fixed the issue of type conversion from TPCDS TIME type column to numeric type

athena-jdbc/README.md
Queries will fail if the source table has upper case letters in the name.
Athena queries are converted to lower case. This causes a mismatch between the Athena query and the source database, and returns an error like "table not found".
For example, if you have the MySQL table "myTable", Athena queries will fail. The table must be renamed "mytable" or users could create a view with a lower case name.
Added a point to the Limitations section
=> Add limitation noting that Athena queries are lower-cased

athena-redis/README.md, athena-redis/etc/test-config.json, athena-redis/pom.xml, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/integ/RedisIntegTestHandler.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/lettuce/RedisCommandsWrapper.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/lettuce/RedisConnectionWrapper.java, athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/integ/RedisIntegTest.java
Adding Integration Tests for the Redis Connector. 
Two Redis instances (standalone, and clustered) will be deployed. Just like in the DocDB integ tests, an extra helper lambda will be deployed to populate the test data into the Redis instances.
There are 15 tests in total:
```
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,196.281 s - in com.amazonaws.athena.connectors.redis.integ.RedisIntegTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19:58 min
[INFO] Finished at: …
```
=> Add Redis Integ Tests

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/CompositeHandler.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/MetadataHandler.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/MetadataRequest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandlerTest.java
If Env variable `glue_catalog` is blank, the glue catalog used should be the account where the lambda function exists. This isn't case for Cross account federated queries:
1. Account A executes cross account federated query to use Account B's function
2. Account B's function will then try to read the glue catalog of Account A by default
This change will update step 2 so that Account B's function, when invoked by Account A, will read Account B's glue catalog by default.
=> Fix Default Glue Catalog

tools/publish.sh
Updating the S3 bucket policy in the publish script to contain `aws:SourceAccount` context key to address confused deputy issue. 
Reference to SAR docs with example policy using `aws:SourceAccount`: https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-how-to-publish.html#publishing-application-through-aws-console
=> Update S3 Bucket Policy

athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/PublishScriptTest.java
Adding a unit test to verify the bucket policy in `publish.sh` is correct. Specifically it should contain the `aws:SourceAccount` since the SAM service principal will be interacting with the bucket on behalf of the calling identity.
=> Add test for bucket policy in publish.sh

README.md
Initially disappointed, thinking Federated Queries were not available in my region, (eu-north-1), but appears they are according [to this link](https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source.html) (Considerations and Limitations section) ). Thus I've updated the description of availability to quote the page and link back to the documentation where Athena v2 is supported.
=> Update README.md with supported regions

athena-example/README.md
Example query was using incorrect `LAMBDA_INVOKE` syntax, rather than just `LAMBDA`
=> Fix example query UDF syntax

athena-federation-integ-test/src/main/java/com/amazonaws/athena/connector/integ/stacks/ConnectorStack.java, athena-redis/README.md, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandler.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisRecordHandler.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/integ/RedisIntegTestHandler.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/lettuce/RedisConnectionFactory.java, athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandlerTest.java, athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/RedisRecordHandlerTest.java, athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/integ/RedisIntegTest.java
Adding support to Redis Connector to allow input of custom redis logical database number (1,2,3,...) via new glue table property flag `redis-db-number`
Also fixing integ tests. Previous shortened lambda function arn input is no longer valid when creating Athena Catalog.
=> Add support for custom redis db number

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/throttling/DynamoDBExceptionFilter.java
DDB tables using On Demand capacity can receive RequestLimitExceeded exceptions if their call rate it too high. The connector needs to handle this exception in order to backoff instead of failing the query.
=> Adding RequestLimitExceededException to throttling invoker

athena-snowflake/README.md, athena-snowflake/athena-snowflake.yaml
None
In a recently deployed [AthenaSnowflakeConnector](https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaSnowflakeConnector), there is no option named **PartitionLimit**, which is a required option to run queries from Athena Query Console. 
This option takes an integer value to limit the number of partitions and sets it to an environment variable named **partitionlimit** in the lambda configuration. 
In the PR, the issue is fixed and tested.
=> Add PartitionLimit option to configure the snowflake connector via SAR

athena-cloudwatch/src/test/java/com/amazonaws/athena/connectors/cloudwatch/integ/CloudwatchIntegTest.java, athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/integ/DocDbIntegTestHandler.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/integ/DocDbIntegTest.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DdbTableUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDbIntegTest.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/integ/ElasticsearchIntegTest.java, athena-federation-integ-test/src/main/java/com/amazonaws/athena/connector/integ/IntegrationTestBase.java, athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/integ/HbaseIntegTestHandler.java, athena-hbase/src/test/java/com/amazonaws/athena/connectors/hbase/integ/HbaseIntegTest.java, athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/integ/MySqlIntegTest.java, athena-postgresql/etc/test-config.json, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/integ/PostGreSqlIntegTest.java, athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/integ/RedisIntegTest.java, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/integ/RedshiftIntegTest.java, athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/integ/TimestreamIntegTest.java
Add datatype conversion integration test suite and implementation for PostgreSQL.
=> Enhance integration test suite

athena-elasticsearch/athena-elasticsearch.yaml
Add cloudformation support on CloudFormation template for VPC on OpenSearch cluster.
=> adding option for VPC config on elasticsearch connector

athena-snowflake/athena-snowflake.yaml
Updated the athena-snowflake.yaml file to provide the correct description. The current description states "This connector enables Amazon Athena to communicate with your Teradata instance(s) using JDBC driver" which could confuse end-users using the Athena Snowflake connector from the Serverless Application Repository or in Lambda.
=> Corrected athena-snowflake.yaml description

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java, athena-sqlserver/src/test/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandlerTest.java
*Issue #INC00001064, Sqlserver Connector Generating $PARTITION Clauses With Nulls.*
*Included partition information to the block to fix null issue while forming the query for partitioned table,
modified corresponding mockito test case as well.*
=> Fix for Sql Server partition issue

.github/workflows/publish_to_maven_central.yml
Publish the child sdk project first before publishing the parent.
=> mvn stuff: flip the ordering of the deploy

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandler.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseRecordHandler.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseUtil.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandlerTest.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/integ/AzureSynapseIntegTest.java
*Issue # INC00001062 : External Table Access Issue In Azure Server Less Environment (Synapse) (Issue Raised Directly By Client)
The issue has been raised from JDBC Driver when we try to access table metadata, so avoided getColumns() method call in case of Azure Server less environment. 
After fixing this, got another issue from driver i.e @@TRANCOUNT' is not supported
In JdbcRecordHandler, refactored conn.commit() to if condition to resolve it.
=> Fix for External table access issue in Azure Server less environment

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java, athena-sqlserver/src/test/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandlerTest.java
*Issue # INC00001068, SQL Server Customer Sees Roles/Users Instead Of Data:*
*In Athena Data window, Database is showing all the schema names along with roles(predefined). Now we have overridden the method doListSchemaNames() in SqlServerMetaDataHandler to display only user defined schema names*
=> Added fix to show only user defined schemas in Athena Data window

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java
The content length was not being set before while spilling to s3.
Since the s3 client method putRequest() is seeing an InputStream, it doesn't
know that it is reading from a byte array and it will buffer again to find
the length.
See this: https://docs.aws.amazon.com/codeguru/detector-library/java/s3-object-metadata-content-length-check/
=> S3BlockSpiller: fix double buffering bug

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java
Fix 1:
GlueFieldLexer: handle Glue set type
GlueFieldLexer before would fail on the set type, but it should really just be treated as an array would be treated.
Fix 2:
GlueFieldLexer: refactor and fix lexing logic
The previous version of the code hardcoded the number of inner end fields (">") to consume in the parent enclosing struct.
This doesn't work for all situations (see the test added).
The right way to do this is to actually just consume the closing fields properly whenever we build a complex type.
This avoids us having to try to figure out how many of these to consume later in an enclosing struct.
Unified and simplified the calling paths as well.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> GlueFieldLexer: handle Glue set type and fix lexComplex logic

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/DefaultGlueType.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueTypeParser.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandler.java
Adds support for all of the following forms of decimal:
"decimal"
"decimal(12,123)"
"decimal(23,111,128)"
This change required a refactoring of DefaultGlueType that removes its use of enum.
The usage was enum seemed to be only for the purposes of the static initialization of the hash map, which is not necessary since we can just use Map.of which achieves the same thing with less code.
An extra level of indirection is also removed now that we just return "ArrowType"s from the DefaultGlueType methods rather than returning "DefaultGlueType".
Issue #664
=> GlueFieldLexer: Add decimal support

athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamClientBuilder.java, athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamMetadataHandler.java, athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandler.java, athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TimestreamClientBuilderTest.java, athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/integ/TimestreamIntegTest.java
https://github.com/awslabs/aws-athena-query-federation/issues/733
Introducing a user-agent field to the client configuration we attach to the Timestream SDK clients (write and query).
=> Adding User Agent field to Timestream SDKs (Query and Write)

athena-dynamodb/README.md, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBRecordMetadata.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DDBTypeUtilsTest.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/DefaultGlueType.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueTypeParser.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandler.java
This `disable_projection_and_casing` variable supports 3 modes:
- auto
- This disables projection and casing when we see a previously unsupported type
and we see that the user does not have column name mapping on their table.
- true
- This disables projection and casing unconditionally.
This is useful when users have casing in their ddb column names but do not want to
specify a column name mapping at all.
- false
- This enables projection and casing unconditionally.
This is useful when the users want projection enabled (mainly for bandwidth and latency)
and are not worried about their columns with casing or already have a column name mapping
for those columns.
Caveats with setting this to true or auto:
- May incur higher bandwidth usage depending on your query.
This not a problem if your …
=> Add `disable_projection_and_casing` to deal with casing issues. Also undoes the revert of the Glue Lexer revert.

athena-elasticsearch/README.md, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchFieldResolver.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchSchemaUtils.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchRecordHandlerTest.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchSchemaUtilsTest.java
Support list of struct type for infer schema.
Example:
Data:
{
"objlistouter": [{
"objlistinner": [{
"title": "somebook",
"author": "author"
}],
"field": "field"
}]
}
mapping:
{
"_meta": {
"objlistouter": "list",
"objlistouter.objlistinner" : "list"
}
}
=> elastic search support list of struct type for infer schema

athena-dynamodb/README.md, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java
Since `auto` is mostly the same as `false`, we can limit the options to just
`auto` and `always`.
=> Simplify options for `disable_projection_and_casing`

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandlerTest.java
Add the partition columns to the schema so that creating Glue
supplemental metadata with partition keys actually works with data
sources that support partitioned Glue supplemental metadata.
=> Add partition columns in Glue Metadata to schema

athena-oracle/README.md, athena-oracle/athena-oracle.yaml, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleConstants.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleRecordHandler.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactoryTest.java
*Issue INC00001066 #,Improve Oracle Connector To Support SSL Connections To The Oracle Db*
Implemented SSL based connection logic in the connector.  
The current version of oracle connector supports ssl based connection for Amazon RDS instances only.
=> Implemented SSL based connection logic in the oracle connector

athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamType.java
- Issue https://github.com/awslabs/aws-athena-query-federation/issues/752
- Boolean types would cause Athena queries to fail. This adds support for Timestream's boolean type
752
Testing was done in a dev aws account. Timestream is difficult to work with, ran this script to get some test data:
```
import boto3
import time
class Timestream:
def __init__(self):
self.write_client = boto3.client('timestream-write')
self.query_client = boto3.client('timestream-query')
self.db_name = 'sample-db'
self.table_name = 'table_with_booleans'
def create_table(self):
self.write_client.create_table(
DatabaseName=self.db_name,
TableName=self.table_name,
RetentionProperties={
'MemoryStoreRetentionPeriodInHours': 1,  # 0 is not valid
'MagneticStoreRetentionPeriodInDays': 365
}, …
```
=> Timestream Connector Boolean Type Support

athena-federation-sdk/README.md
*Issue #, if available:* none
*Description of changes:* `java.lang.Int` -> `java.lang.Integer`
=> Fix a typo in README.md of athena-federation-sdk

athena-federation-sdk/pom.xml, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockUtilsPropertiesTest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/FieldsGenerator.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/ValuesGenerator.java, athena-hbase/pom.xml, pom.xml
Dependency changes:
- Upgraded JUnit to Jupiter
- Added JQwik
Added BlockUtilsPropertiesTest
Found and fixed the following issues with BlockUtils (via the added test above):
- Null values not being preserved in any container types (Lists, Maps, Structs)
- List of maps was not supported (threw an exception)
- Struct of maps was not supported (thew an exception)
- Incorrect casting of primitive types (thew an exception)
- Struct of DateMilli fields was not working (threw an exception)
Remaining issues:
- List and Map of TimeStamp*TZ fields are not working right now because of a bug in Arrow. - This is an existing problem. - Test is not generating and testing these fields right now (commented out).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> Data Integrity: Add generative testing and fixes

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java
Previously the code was trimming the white space around String values.
This is not right since it is valid to have Strings with white spaces around them as values.
=> athena-jdbc: Don't trim string values

athena-elasticsearch/athena-elasticsearch.yaml, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchRecordHandler.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchRecordHandlerTest.java
Elastic search connector enable pagination query data from get records. This will allow use to bypass max_result_window settings.
By default, max_result_window set to 10,000. We can't query data more than 10,000. Enable pagination we can read all rows.
Test done through integration test and manually test on sample cluster with max_result_window = 1,000 and data rows 4907
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html
Link to related tickets:
https://github.com/awslabs/aws-athena-query-federation/issues/461
https://github.com/awslabs/aws-athena-query-federation/issues/491
=> Elastic search connector enable pagination query data from get records

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java
This patch converts inclusive ranges for DDB key conditions to use BETWEEN.
Also tests have been added to ensure that we do not convert the mixed inclusion ranges to BETWEEN.
Also fixes a long standing buggy test that has been masked over by
automatic type inference failover in: DynamoDBRecordHandlerTest.java
This patch is a safer version of this prior work.: https://github.com/awslabs/aws-athena-query-federation/pull/375
=> DDB: Add BETWEEN support

athena-dynamodb/pom.xml, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DDBFieldResolverTest.java, athena-elasticsearch/pom.xml, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchFieldResolver.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchFieldResolverGenerativeTest.java, athena-federation-sdk/pom.xml, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/FieldResolver.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockUtilsPropertiesTest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/FieldResolverTest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/CustomFieldVector.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/FieldsGenerator.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/ValuesGenerator.java
Added FiedResolverTest, DDBFieldResolverTest and ElasticsearchFieldResolverGenerativeTest
Found and fixed the following issues in FieldResolver:
1) Values not being set correctly for maps (throws exception)
Found and fixed the following issues in DynamoDBFieldResolver and ElasticsearchFieldResolver: 
1) Null values not being set correctly for nested lists (eg. Lists of lists) (incorrect behavior where a null list would be represented as a list with a null value) 
2) Values not being set correctly for maps (throws exceptiton)
=> Data Integrity: Add generative tests for FieldResolver, DynamoDBFieldResolver, ElasticsearchFieldResolver.

athena-jdbc/pom.xml
Apache Commons Text performs variable interpolation, allowing properties to be dynamically evaluated and expanded. The standard format for interpolation is "${prefix:name}", where "prefix" is used to locate an instance of org.apache.commons.text.lookup.StringLookup that performs the interpolation. Starting with version 1.5 and continuing through 1.9, the set of default Lookup instances included interpolators that could result in arbitrary code execution or contact with remote servers. These lookups are: - "script" - execute expressions using the JVM script execution engine (javax.script) - "dns" - resolve dns records - "url" - load values from urls, including from remote servers Applications using the interpolation defaults in the affected versions may be vulnerable to remote code …
=> Fixed @ CVE-2022-42889

tools/validate_connector.sh
*Issue #, if available:https://github.com/awslabs/aws-athena-query-federation/issues/798
the wrong jar name in tools/validate_connector.sh
=> Fix the wrong jar name in tools/validate_connector.sh

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandler.java
Add the ability to disable projections and casing in order to support querying docdb with mixed casing column names.
To enable, set the "disable_projection_and_casing" environment variable on the athena-docdb lambda to "true"
Issue: #463
=> athena-docdb: add disable_projection_and_casing env var

athena-cloudwatch/athena-cloudwatch.yaml
athena-cloudwatch.yaml was broken just like the athena-dynamodb.yaml from the recent change to add the LambdaRole.
=> Fix cloudwatch yaml

athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/ValuesGenerator.java
Different JDKs have different internal representations of Strings.
When the JDK has a non UTF8 representation (like UTF16), these tests were setting invalid byte values for Arrow string fields/values which are expecting UTF8 encoded bytes.
This was causing test failures because it caused keys that were expected to be unique to not be unique since invalid UTF8 strings can be considered equal (UTF16 can't just be casted to UTF8).
The fix here is to make sure that we use getBytes(StandardCharsets.UTF_8) to ensure that we get the byte encoding that we want.
=> ValuesGenerator: fix String:getBytes() issue

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/domain/spill/SpillLocationVerifier.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/domain/spill/SpillLocationVerifierTest.java
improve error message with invalid spill bucket
https://github.com/awslabs/aws-athena-query-federation/issues/415
=> improve error message with invalid spill bucket

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AWSRequestSigningApacheInterceptor.java
[Issue 510](https://github.com/awslabs/aws-athena-query-federation/issues/510)
[Issue 340](https://github.com/awslabs/aws-athena-query-federation/issues/340)
AWS Signer: workaround for null content failure by setting an empty body. [See here for the discussion and suggested fix](https://github.com/aws/aws-sdk-java/issues/2078).
=> AWS Signer set empty content

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java, athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java
*Issue # INC00001086, Check only last row count with connector snowflake.
Added table_schema condition in COUNT_RECORDS_QUERY,to check for the table in that particular schema and give the correct row count.
=> Added table_schema condition in COUNT_RECORDS_QUERY to get the correct row count.

athena-synapse/athena-synapse.yaml, athena-synapse/etc/test-config.json
*Issue # INC00001084, Being able to set the Lambda Role in AthenaSynapseConnector.
Added support for optional LambdaRole parameter for AthenaSynapseConnector. The Lambda function created will now allow users to select own role.
=> Add support for optional LambdaRole parameter for AthenaSynapseConnector

athena-postgresql/athena-postgresql.yaml
We need to add an extra env variable for connection string manually to the lambda function for Athena to access any database. By allowing to use different handler we can use the Default connection string when we only have one postgres instance.
=> Add CompositeHandler parameter to CF template

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java
*Issue #, if available:* https://github.com/awslabs/aws-athena-query-federation/issues/399
As described in the issue, dynamodb connector breaks when there is `null` values in complex structures. There is a comment in the original issue mentioning that [this PR](https://github.com/awslabs/aws-athena-query-federation/pull/780) fixed the issue, but I'm still facing the same described error when my data structure contains `null`.
I've tested manually the connector with the following change, and it works fine.
I would like some feedback to know if this is an acceptable change, and if anything else would be needed for this PR to be accepted.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Avoid errors on null values for dynamodb

athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryConstants.java, athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandler.java
*Issue # INC00001088, Implemented Pagination in  AthenaGoogleBigQueryConnector.
Description of changes:
The connector was throwing an exception when BigQueryConstants.MAX_RESULTS was exceeded instead of correctly returning all of the results.
With the new pagination logic its handled by returning paginated results.
=> Implemented pagination logic in AthenaGoogleBigQueryConnector

athena-arrow-java-dist/arrow-dataset-10.0.1.pom, athena-arrow-java-dist/pom.xml, pom.xml
athena-arrow-java-dist is a custom distribution of arrow built with GCS support enabled.
See this branch for changes to arrow and instructions for how to build: https://github.com/henrymai/arrow/commits/apache-arrow-10.0.1-amzn
This patch also bumps the arrow dependency version to 10.0.1.
We need a separate module project for this because this is the cleanest way to have maven depend on a dependency that is checked in.
- See this link for reference: https://stackoverflow.com/a/7908872
Eventually if Arrow turns on GCS support for their official distribution, we can get rid of this.
=> Add athena-arrow-java-dist

athena-timestream/athena-timestream.yaml
- Previously, timestream:* actions were applied to the lambda's policy
- Now, we reduce to specific read operations for least privilege
Testing Done:
Deployed the connector to an aws account and ran the following queries against an existing timestream table:
Query 1 - describe the table
```
describe `lambda:timestream-least-privilege`.`timestream-db`.`timestream-store-sales-mini`
```
I see all the results.
Query 2 - select * (no projection)
```
select * from "lambda:timestream-least-privilege"."timestream-db"."timestream-store-sales-mini" limit 500;
```
This works too.
Query 3 - select with projection
```
select ss_cdemo_sk, ss_promo_sk from "lambda:timestream-least-privilege"."timestream-db"."timestream-store-sales-mini" limit 500;
``` …
=> Reduce Privileges of Lambda Role for Timestream

athena-saphana/athena-saphana.yaml
Fix athena-saphana.yaml after changing from maven-assembly to maven-shade
=> Fix athena-saphana.yaml after changing from maven-assembly to maven-shade

.github/workflows/maven_push.yml
We're using self hosted runners, so try with -T8
=> Update maven_push.yml to build with 8 cpus

.github/workflows/codeql-analysis.yml
Error:
```
Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
```
=> codeql-analysis.yml: try to fix permissions error

athena-dynamodb/athena-dynamodb.yaml
Unable to Create DynamoDB Connectors if Custom Lambda Role is Used.
Added Condition Check for Function Policy to create only if Custom Function role is passed to SAM Resource
=> Added Condition for Function Execution Policy

athena-msk/athena-msk.yaml, athena-msk/etc/test-config.json, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskConstants.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskUtils.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandlerTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskUtilsTest.java
Rename auth_type options to be more descriptive.
- The original naming does not make it apparent to the user that most of these options are just different kinds of SASL options.
- Also uses enums to enhance safety.
Also fixes a bug with the FunctionExecutionPolicy when a LambdaRole is provided.
- Thanks to @adithyapathipaka for initially finding and fixing this in the DDB yaml.
=> athena-msk: rename auth_type options to be more descriptive

athena-hbase/pom.xml
athena-hbase/pom.xml: use netty.version
=> athena-hbase/pom.xml: use netty.version

athena-saphana/athena-saphana.yaml, athena-saphana/pom.xml
There's an issue with the maven-shade-plugin with the saphana jdbc driver not being able to load at runtime because of java versions.
=> athena-saphana: use maven-assembly-plugin again

athena-aws-cmdb/athena-aws-cmdb.yaml, athena-cloudera-hive/athena-cloudera-hive.yaml, athena-cloudera-impala/athena-cloudera-impala.yaml, athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml, athena-cloudwatch/athena-cloudwatch.yaml, athena-datalakegen2/athena-datalakegen2.yaml, athena-db2/athena-db2.yaml, athena-docdb/athena-docdb.yaml, athena-dynamodb/athena-dynamodb.yaml, athena-elasticsearch/athena-elasticsearch.yaml, athena-google-bigquery/athena-google-bigquery.yaml, athena-hbase/athena-hbase.yaml, athena-hortonworks-hive/athena-hortonworks-hive.yaml, athena-msk/athena-msk.yaml, athena-mysql/athena-mysql.yaml, athena-neptune/athena-neptune.yaml, athena-oracle/athena-oracle.yaml, athena-postgresql/athena-postgresql.yaml, athena-redis/athena-redis.yaml, athena-redshift/athena-redshift.yaml, athena-saphana/athena-saphana.yaml, athena-snowflake/athena-snowflake.yaml, athena-sqlserver/athena-sqlserver.yaml, athena-synapse/athena-synapse.yaml, athena-teradata/athena-teradata.yaml, athena-timestream/athena-timestream.yaml, athena-tpcds/athena-tpcds.yaml, athena-udfs/athena-udfs.yaml, athena-vertica/athena-vertica.yaml
*Issue #, if available:* #365
Adding an optional `PermissionsBoundaryARN` to connectors where it does not already exist (it look this was added for the `athena-synapse` connector only as a part of #808).  This is to add and make consistent across all of the remaining connectors available in this repo.
=> Adding optional permissions boundary parameter

athena-msk/athena-msk.yaml, athena-msk/pom.xml, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskConstants.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandler.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskUtils.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/GlueRegistryReader.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/dto/TopicSchema.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/serde/MskJsonDeserializer.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandlerTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskRecordHandlerTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskUtilsTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/MskCsvDeserializerTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/MskJsonDeserializerTest.java
Normally Athena queries are of the following structure:
`SELECT * FROM <catalog name>.<schema name>.<table name>`
The previous version of this connector did not map this structure properly onto the structure for querying schemas in the Glue Schema Registry; specifically it did not leverage the `<schema name>` part of the query at all.
With this patch, this is how we map to the Glue Schema Registry now:
`SELECT * FROM <catalog name for msk>.<glue registry name>.<glue schema name>`
And then inside the Glue Schema, the "topicName" corresponds to the Kafka topic name.
This means that the registry ARN environment variable is no longer necessary and has been removed, since the registry is now contained in the query structure itself.
This means that we also had to properly implement …
=> Fix MSK connector issues

athena-msk/README.md, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandler.java
Fixes the following bugs:
- When there is only one page (only start), we would fire an additional extraneous glue query before Stream.iterate() would terminate.
- When there are multiple pages, the last page would be missing, because Stream.iterate excludes the last result that violates the iteration condition.
The fix is to have Stream.iterate() terminate only after the last page is included by changing the logic such that we just don't fire a request when the nextToken() is null by returning null in that situation to have Stream.iterate() terminate on that condition instead (which would exclude the terminating null from our Stream as well).
Also added link to the README.md
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> athena-msk: Fix bugs with Glue request pagination

athena-elasticsearch/pom.xml, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsRestHighLevelClient.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchRecordHandler.java
clients newer than 7.10.2 are not compatible with opensearch
See: https://stackoverflow.com/a/72237262
=> athena-elasticsearch: downgrade elasticsearch client

athena-cloudera-impala/src/main/java/com/amazonaws/athena/connectors/cloudera/ImpalaMetadataHandler.java, athena-cloudera-impala/src/test/java/com/amazonaws/athena/connectors/cloudera/ImpalaMetadataHandlerTest.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/domain/TableName.java
With this change, if the user specifies the connection string without specifying a database, they will be able to query any table across any database within their impala cluster that their authenticated user has access to.
=> athena-cloudera-impala: support querying tables across databases

athena-cloudera-hive/src/main/java/com/amazonaws/athena/connectors/cloudera/HiveMuxCompositeHandler.java, athena-cloudera-impala/src/main/java/com/amazonaws/athena/connectors/cloudera/ImpalaMuxCompositeHandler.java, athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MuxCompositeHandler.java, athena-db2/src/main/java/com/amazonaws/athena/connectors/db2/Db2MuxCompositeHandler.java, athena-hortonworks-hive/src/main/java/com/amazonaws/athena/connectors/hortonworks/HiveMuxCompositeHandler.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcCompositeHandler.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/DatabaseConnectionConfigBuilder.java, athena-mysql/src/main/java/com/amazonaws/athena/connectors/mysql/MySqlMuxCompositeHandler.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMuxCompositeHandler.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMuxCompositeHandler.java, athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftMuxCompositeHandler.java, athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaMuxCompositeHandler.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMuxCompositeHandler.java, athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMuxCompositeHandler.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseMuxCompositeHandler.java, athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataMuxCompositeHandler.java
In the situation where there is only a `default` connection specified, just use the non mux versions of the handlers.
This allows the user to not have to set a `<datasource_name>_connection_string` and only have the `default` connection string specified.
This patch addresses issues: #827, #683
=> Simplify MuxCompositeHandler usage for single connections

athena-cloudera-impala/athena-cloudera-impala.yaml
This allows users to set the `KmsKeyArn` for the connector lambda that is created by SAR.
=> athena-cloudera-impala: Add LambdaEncryptionKmsKeyARN

tools/bump_versions/common.py
zero padding is breaking semantic versioning on SAR
=> bump_versions/common.py: don't generate week with zero padding

athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandler.java
Fixing null pointer exception on timestream. Previously, we always set this `value.isSet = 1` regardless if we actually have data or not
If we have a union of schema, this will give us a null pointer exception when one of the fields doesn't exist in a row.
Example:
row1:
{"Dimensions": [{"Name":"host","Value":"aaa"}],"MeasureName":"cpu_utilization","MeasureValue":"77.8","MeasureValueType":"DOUBLE","Time":"1673931494255"}
row2:
{"Dimensions": [{"Name":"host","Value":"aaa"}],"MeasureName":"comment","MeasureValue":"bbb","MeasureValueType":"VARCHAR","Time":"1673931494255"}
We will have a union schema in table as 
|host|measure_name|time|measure_value::double|measure_value::varchar|
|-|-|-|-|-|
For row 1, it doesn't have `measure_value::varchar` field and will result a null pointer exception. …
=> fix null pointer on timestream

athena-msk/athena-msk.yaml, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskUtils.java
*Issue #, INC00001094
Support for sasl ssl plain for managed kafka cluster like confluent cloud.
Support for msk connector without vpc setup.
=> Athena-msk: support for sasl ssl plain for managed kafka cluster like confluent cloud

.gitignore, athena-google-bigquery/athena-google-bigquery.yaml
athena-google-bigquery: make subnets and security groups optional to address issue #737 
And also:
Add .jqwik-database to .gitignore
=> athena-google-bigquery: make subnets and security groups optional

athena-postgresql/athena-postgresql.yaml
Add option to select custom lambda role when deploying the PostgreSQL connector
=> Add option to select custom lambda role when deploying the PostgreSQL connector

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DDBTypeUtilsTest.java
Customer has one table which has a column that consists of a few structs and arrays and when using DynamoDB Connector,  is receiving "NullpointerException", which is preventing customer from accessing any of the DynamoDB tables in Athena.
Treat nulls properly: nulls are effectively the same type as any other element in the List.
=> athena-dynamodb: Added logic to handle Null value within List or Set

athena-gcs/assembly.xml, athena-gcs/athena-gcs.yaml, athena-gcs/pom.xml
The size recently blew up with some of the dependency updates which
causes AWS Lambda to error out upon deploying since it tries to unpack
the jar.
Using maven assembly we retain the jar files inside rather than storing
them as unpacked class files within the main jar.
This results in a smaller unpacked jar upon deploying on AWS Lambda,
since when unpacked, the classes are still within jars.
=> athena-gcs: Use maven assembly instead of shade

athena-gcs/athena-gcs.yaml, athena-gcs/pom.xml, athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsCompositeHandler.java, athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsConstants.java, athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsUtil.java, athena-gcs/src/test/java/com/amazonaws/athena/connectors/gcs/GcsCompositeHandlerTest.java
Uses jna to set the environment for native calls and avoids any possibility of users setting the wrong values.
=> athena-gcs: eliminate reliance on external environment variables

.github/workflows/maven_push.yml
Running the build workflow for both push and pull request open is redundant and is a waste of time.
=> Run the build workflow only for push

tools/bump_versions/common.py
Hitting the http public api isn't reliable because of throttling issues with it.
=> bump_versions/common.py: use gh cli instead of curl

athena-mysql/athena-mysql.yaml, athena-sqlserver/athena-sqlserver.yaml
Add `LambdaRoleARN` parameter to athena-sqlserver and athena-mysql connectors
This adds the ability to specify an ARN of the execution role for the deployed lambda connector. If none is supplied, then a role is generated with same policies as previous behaviour. 
These changes are based on the changes made to achieve the same result for the athena-postgresql connector in #995.
See also #365.
=> Add LambdaRoleARN parameter to sqlserver and mysql connectors

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockUtilsTest.java
Simplifies the code to avoid using daysBetween to calculate the epoch days.
Also adds a test to prevent regressions in the future.
Test failure without the fix:
[ERROR] Failures:
[ERROR]   BlockUtilsTest.fieldToString:157 expected:<...], col3=[18339, 1825[9]]}> but was:<...], col3=[18339, 1825[8]]}>
The epoch days is off by 1 without the fix.
Credits go to @akuzin1 for testing and pinpointing where this problem was occurring.
=> BlockUtils: Fix epoch day calculation

athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadata.java, athena-gcs/src/test/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadataTest.java
The GCS connector was not able to list the partition folder if we are uploading it to the GCS bucket directly.
fixed the issue by listing down the file path and getting partition folder from complete file name.
e.g. getting file name as year=2000/month1/test.parquet
so, by doing substring in last index of '/' we are getting partition folder path as "year=2000/month1/".
=> GCS connector fix for uploaded partition folder issue

athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaMetadataHandler.java, athena-kafka/src/test/java/com/amazonaws/athena/connectors/kafka/KafkaMetadataHandlerTest.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandler.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandlerTest.java
Add pagination for MSK doGetSplits
- Around 40-50k splits will cause the response for doGetSplits to exceed
the 6mb limit set by lambda
- Here I set the max splits per request to 1000.
- This patch adds pagination support for doGetSplits to avoid exceeding
the max response size and updates tests
- We then also have to sort the partitions by id as they come in,
because the consumer can fetch them in different orders sometimes.
Without sorting, the continuation token loses meaning
=> [MSK + Kafka] Add pagination support on doGetSplits()

.github/workflows/maven_push.yml
- First, we need to add back pull_request, since outside contributors won't hit the push trigger when they open a pull request, since they do it from their own forks.
- Second, in order to avoid duplicate workflows running, we leverage this skip-duplicate-actions from the Github Action marketplace to avoid running duplicate workflows in multiple different situations.
=> .github/workflows/maven_push.yml enhancements

.github/workflows/codeql-analysis.yml
Apply the same change that was done for maven_push.yml to codeql-analysis.yml to skip unnecessary actions.
=> codeql-analysis.yml: skip duplicate actions

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/domain/predicate/Constraints.java
Constraints.close() does not actually throw Exception, so there's no need to declare it.
Declaring it unnecessarily causes users of this class to be forced to catch or forced to declare that it throws Exception.
=> domain.predicate.Constraints: Fix close() method signature

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBTableResolver.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java
Collectors.toList() will already provide an immutable List and this avoids issues with certain Spark distributions having a different version of Google Guava.
=> Don't depend on Google Guava toImmutableList

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java
In Athena v3, we are pushing down more predicates than we were in v2, which exposed an issue with how the athena-dynamodb connector was handling push downs for sort keys.
DDB does not allow sort keys to have more than one condition associated with them, so when we get SortedRangeSet push downs with upper and lower bounds from Athena, we were applying both bounds and then getting an error upon querying DDB.
In order to resolve this issue, we can simply just apply only one of the bounds when we are dealing with sort keys. In this implementation, upper bounds were chosen as the one that takes priority when both upper and lower bounds are present since upper bounds should theoretically filter more than a lower bound.
Issue #1089
By submitting this pull request, I confirm that you can use, …
=> athena-dynamodb: Improve ddb sort key pushdown handling

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBRecordMetadata.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java, athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java, athena-federation-sdk/README.md, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/ArrowSchemaUtils.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/ArrowTypeComparator.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtil.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/SupportedTypes.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/ArrowSchemaUtilsTest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockUtilsTest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtilTest.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/serde/v2/ArrowSerDeTest.java, athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsUtil.java, athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadata.java
Adding support for TIMESTAMPMICROTZ including various refactoring and bug fixes for existing TIMESTAMPMILLITZ support.
commit 526400f3b7266c09a0624b90c476529340484aaa
Add support for TIMESTAMPMICROTZ
commit 32e0bccf7b80c7e8b2ccc452cfb141ee78a761b8
Add support unpacked timestamps with timezones
- Refactor how we write timestamps to not expose packing publicly.
- Added a switch to disable packing in DateTimeFormatterUtil.
- Updates DateTimeFormatterUtil.constructZonedDateTime to deal with both
packed and unpacked timestamps.
- Fixes and refactoring of the GCS connector code when
handling schema conversions for Time and Timestamp types.
- [...]StorageMetadata.java was not preserving timezones for
Timestamp types previously.
- Gets rid of joda time usage since it looks like the only reason it …
=> Adding support for TIMESTAMPMICROTZ including various refactoring and bug fixes for existing TIMESTAMPMILLITZ support.

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java, athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java
INC00001105 Customer Is Hitting An Exception From The Snowflake Connector
athena-snowflake update from rs.getInt() method call to rs.getLong() method call of result set object to retreive more record count of a table.
=> athena-snowflake update from rs.getInt() method call to rs.getLong() to retreive more record count of a table

athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadata.java, athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataMetadataHandler.java
athena-gcs: Fix StorageMetadata::getCompatibleFieldType
- The previous version of this code was converting all
ArrowType.Timestamp without timezones into ArrowType.Date.
This patch returns us to that past behavior in
the athena-gcs connector to avoid issues with the Athena Console.
** Note that it doesn't look like we ever hit the
TIMESTAMPMILLITZ case in the past, because that case immediately
would throw an exception in the connector itself before any
response is returned to the Athena Console.
- Fix an incorrect logging message in TeradataMetadataHandler
=> athena-gcs: Fix StorageMetadata::getCompatibleFieldType

athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsUtil.java, athena-gcs/src/test/java/com/amazonaws/athena/connectors/gcs/GcsUtilsTest.java
Fixes the coerce to actually test what really gets read out from an Arrow vector rather than made up types in the test to properly exercise coerce.
Also updates coerce to return LocalDateTime in the Time Long case since it is a more modern java type with higher retained precision.
=> athena-gcs: Update GcsUtilsTest for coerce

.github/workflows/cut_release.yml
workflows/cut_release: Use ubuntu-latest instead of self-hosted
Our self-hosted runners are missing `gh cli`
=> workflows/cut_release: Use ubuntu-latest instead of self-hosted

athena-redshift/pom.xml
addresses #1156 and an internal ticket to add support for redshift serverless
This change bumps the redshift jdbc driver to the latest supported driver. Checked with former redshift jdbc driver team member that the driver is backwards compatible and more efficient.
=> bump redshift to preferred driver version

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java, athena-federation-sdk/pom.xml, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/credentials/CrossAccountCredentialsProvider.java
Prior to this change, we supported using cross-account Glue data catalogs to fetch metadata for DynamoDB tables. However, we did not have any support for allowing customers to query a cross-account DynamoDB table, so this provided very little value.
With this change, customers can now query DynamoDB tables across accounts, both with and without the use of a cross account Glue data catalog. To do so, the customer adds an environment variable to their connector, `cross_account_role_arn`. They also have to perform standard IAM configurations for cross-account resource access. Specifically, the account containing the DynamoDB table (account A) adds a role which the calling account (account B) with the connector has permissions to assume, containing a policy against the table and its indices …
=> [DynamoDB] Add Cross-Account Functionality

.github/workflows/publish_to_maven_central.yml
-am flag will make sure that we build all the dependencies
=> publish_to_maven_central: use -am flag

.github/workflows/cut_release.yml, tools/bump_versions/common.py
workflows/cut_release: fix release version auto increment
Also removes the explicit -R (repo) specification in gh cli commands.
This isn't necessary since now this is being run straight from a github
action for the given repository.
Removing this makes this easier to test github actions in forked
versions of the repository as well.
=> workflows/cut_release: fix release version auto increment

athena-redshift/athena-redshift.yaml
*Description of changes:* This PR allows the `athena-redshift` connector to be passed a Role ARN for the lambda to use, and allows the role it creates when a role is not passed to write to a spill bucket that uses KMS CMK encryption.
I've tested this in a live environment with the following configurations, asserting that Athena is able to successfully list the schema and execute queries:
* Without using either new parameter - works as expected, no breaking changes, spill bucket uses the `KMS_MANAGED` CDK bucket encryption type
* Passing just a `LambdaRole` parameter - works as expected, correctly skips creating the role in the application manifest, lambda assumes the role arn passed in via the parameter, and is able to spill correctly
* Passing just a …
=> feat(athena-redshift): Support spill buckets using KMS CMK keys, passing role arn for lambda

athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlRecordHandlerTest.java
Test previously was only asserting for order by ascending. Make one of the order by clauses descending for better coverage.
=> [athena-mysql Fix] Add testing for both order by directiosn in MySql test

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/util/PaginatedRequestIterator.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/util/PaginatedRequestIteratorTest.java, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaMetadataHandler.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandler.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskRecordHandler.java, athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamMetadataHandler.java
*Issue #, if available:* [#792](https://github.com/awslabs/aws-athena-query-federation/issues/792)
Because Trino follows Hive naming conventions, where schema names and table names are lower-cased and are case-insensitive, DML queries against our connectors will receive lower-cased versions of schema and table names. This will lead to query failures if the Timestream schema/table are not both in lowercase format.
Example: Database name is "MixedCaseDb" and table name is "tableWithMixedCase".
`SELECT * FROM "lambda:timestream"."MixedCaseDb"."tableWithMixedCase"` will be sent down to Timestream with the schema name `mixedcasedb` and table name `tablewithmixedcase`, which will then fail to resolve because Timestream is case-sensitive.
This PR adds logic to do a …
=> [Timestream] Add case-insensitive lookup to allow queries against cased dbs/tables to succeed

athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchMetadataHandler.java, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchTableName.java, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchTableResolver.java
There are two bugs that this fixes. First, any list tables or list schemas calls would automatically lowercase the resulting log groups and log streams. Second, the existing logic which tried to allow for case insensitive lookups for matching log streams wrongly compared two strings and would always return the first log stream it found, instead of the actual matching log stream.
Correctness tested against miscellaneous mixed case log streams and log groups. Queries are all correct for listing schemas, listing tables, describing tables, and selecting from tables.
Note that queries will return indeterminate results if there are two log groups or log streams with case insensitive name matches. If log stream "asdf" and "ASDF" both exist, "asdf" will be picked. If log stream "asDF" and "ASdf" …
=> [Bug Fix] [athena-cloudwatch] Stop lowercasing all schemas and tables, fix data integrity issue

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/FederationExpressionParser.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcFederationExpressionParser.java, athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlFederationExpressionParserTest.java
Previous logic would append a predicate of arg0 IN (arg1) However, arg1 is always of type array, so it's already surrounded by parentheses. So, just append the predicate as arg0 IN arg1.
I also removed the unnecessary helper method for the recursive jdbc expression parser.
Tested this by running Trino locally and performing miscellaneous queries against a TPCDS table. Initial query which failed:
```
select * from lambda.test.store_sales where ss_item_sk in (ss_store_sk, 2, 3) limit 10;
```
Error:
```
java.sql.sqlexception: Operand should contain 1 column(s): java.lang.RuntimeExceptionjava.lang.RuntimeException: java.sql.SQLException: Operand should contain 1 column(s)at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:117)Caused by: …
```
=> [JDBC Fix] IN predicate with variable expression formed malformed SQL

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsRestHighLevelClient.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchMetadataHandler.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchRecordHandler.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchMetadataHandlerTest.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchRecordHandlerTest.java
Add support for Data Stream for elastic search.
Data Stream contains multiple indices, see following notes for more information.
https://opensearch.org/docs/1.1/opensearch/data-streams/
https://opster.com/guides/opensearch/opensearch-machine-learning/opensearch-data-streams/#How-to-create-data-streams-in-OpenSearch
https://github.com/awslabs/aws-athena-query-federation/issues/511
=> add data stream support for elasticsearch

athena-cloudera-hive/src/main/java/com/amazonaws/athena/connectors/cloudera/HiveMetadataHandler.java, athena-cloudera-hive/src/test/java/com/amazonaws/athena/connectors/cloudera/HiveMetadataHandlerTest.java
This PR is derived from this https://github.com/awslabs/aws-athena-query-federation/pull/935 by @henrymai 
#With this change, if the user specifies the connection string without specifying a database, they will be able to query any table across any database within their impala cluster that their authenticated user has access to.
=> support querying tables across databases for cloudera-hive

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcMetadataHandler.java
Fixes issue where certain jdbc connectors return empty map for getDataSourceCapabilites. This was due to one of the intermediate classes not having the correct inheritance call path.
=> fixing jdbc metadata handler to appropriately call extended classes

athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/RdsTableProvider.java, athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/Ec2TableProvider.java, athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/RdsTableProviderTest.java, athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/Ec2TableProviderTest.java
*Issue #, if available:* https://github.com/awslabs/aws-athena-query-federation/issues/474
```
sql > select instance_id, tags from "lambda:athena-cmdb".ec2.ec2_instances;
#	instance_id	tags
1	i-0bf77b4a77abbcbf2	[{key=Name, value=java c5.9xlarge}]
2	i-0774ea3926f865e7b	[{key=aws:elasticmapreduce:job-flow-id, value=j-L0XIA0QWQ5GC}, {key=aws:elasticmapreduce:instance-group-role, value=MASTER}]
```
=> CMDB connector - Add EC2 and RDS instance tags to output

athena-federation-sdk/pom.xml, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/handlers/CompositeHandlerTest.java, pom.xml
=> Get rid of powermock and mockito.legacy.version entirely

athena-mysql/src/main/java/com/amazonaws/athena/connectors/mysql/MySqlQueryStringBuilder.java, athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlRecordHandlerTest.java
fixing syntax for TOP N queries for mysql connector. 
MySQL doesn't allow NULLS LAST LIMIT 100;
=> fixing mysql connector syntax for top N

athena-google-bigquery/athena-google-bigquery.yaml, athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandler.java, athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQuerySqlUtils.java, athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandlerTest.java
fix for data inconsistency in distinct clause Google BigQuery connector.
This is a quick fix to resolve data inconsistency in distinct clauses. for this fix, we removed multiple splits created by passing limit and offset to read query. we are using a single split as of now. 
we recommend the user pass the where clause for faster results.
=> fix for data inconsistency in distinct clause Google BigQuery connector 

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/DatabaseConnectionConfigBuilder.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/connection/DatabaseConnectionConfigBuilderTest.java
Modified regex for pattern matching secret names, because service linked secrets include the `!` character.
Added test cases as well.
[AWS Secrets Manager secrets managed by other AWS services](https://docs.aws.amazon.com/secretsmanager/latest/userguide/service-linked-secrets.html)
=> Added ! as valid character in Secret, due to syntax of service linked secrets

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java, athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlQueryStringBuilderTest.java
Modified statement that is responsible for adding `IS NOT NULL` clause to generate sql for JDBC connectors.
Prior to change, when evaluating a `not equal to` predicate it would short circuit and not push down all predicates to sql statement.
For Example:
`SELECT * FROM item WHERE i_manufact_id <> 138`
Would be translated to:
`SELECT * FROM item WHERE (i_manufact_id IS NOT NULL)`
This is the result of calling `getSpan()` on `SortedRangeSet`, which returns a Range that is a summary of the lowest lower bound and the highest upper bound that represents this ValueSet.
Therefore, the following ValueSet from statement with `i_manufact_id <> 138` predicate:
```
i_manufact_id=SortedRangeSet{
type=Int(64, true), nullAllowed=false, lowIndexedRanges={
Marker{ …
```
=> Pushing down 'not equal' to predicate

athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2QueryStringBuilder.java, athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeQueryStringBuilderTest.java, athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeRecordHandlerTest.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleQueryStringBuilder.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleRecordHandlerTest.java, athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerQueryStringBuilder.java, athena-sqlserver/src/test/java/com/amazonaws/athena/connectors/sqlserver/SqlServerQueryStringBuilderTest.java, athena-sqlserver/src/test/java/com/amazonaws/athena/connectors/sqlserver/SqlServerRecordHandlerTest.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseQueryStringBuilder.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseQueryStringBuilderTest.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseRecordHandlerTest.java, athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataQueryStringBuilder.java, athena-teradata/src/test/java/com/amazonaws/athena/connectors/teradata/TeradataRecordHandlerTest.java
Certain data sources does not support limit clause, when for these data sources , a limit query is executed in Athena, it throws exception, as currently limit clause is pushed down.  The fix is to solve the error raised due to limit clause pushdown.
=> limit clause pushdown fix for certain data sources

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java, athena-mysql/src/main/java/com/amazonaws/athena/connectors/mysql/MySqlMetadataHandler.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandlerTest.java, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandlerTest.java
*Issue #, if available:* https://github.com/awslabs/aws-athena-query-federation/issues/61
*Description of changes:* In doGetTable method, if a table is not found in the database, then do a lookup for all tables in the database, and then do a local case-insensitive search for table name. 
This is similar to how DynamoDB connector does case-insensitive search https://github.com/awslabs/aws-athena-query-federation/blob/b99bba84302a9299f5d53e3a4da1cb0d9f67ab2e/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBTableResolver.java#L148-L172
Note that if database contains a table with all lowercase letters, then that table will always be returned even if there are other tables with uppercase letters. This is because lowercase table name will be returned in …
=> Case insensitive table name search in JDBC connectors

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java, athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlMetadataHandlerTest.java, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandlerTest.java, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandlerTest.java
When performing case insensitive table name look up for JDBC data sources it is now done on the specific database, while also checking for duplicate table names.
=> Fix case insensitive table name search bug

validation_testing/cdk_federation_infra_provisioning/app/package.json
Reverts awslabs/aws-athena-query-federation#1424
=> Revert "build(deps): bump aws-cdk-lib from 2.63.2 to 2.80.0 in /validation_testing/cdk_federation_infra_provisioning/app"

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-mysql/src/main/java/com/amazonaws/athena/connectors/mysql/MySqlMetadataHandler.java, athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlMetadataHandlerTest.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandlerTest.java, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandlerTest.java
Modified select JDBC connectors to fetch tables, views and materialized views from internal, system tables of underlying data source, to respect user access privileges.
#1464
#1462
#1450 
Metadata returned from JDBC driver cannot be hidden, therefore, user can still see the structure, despite not being able to access if not granted permission. Therefore, all tables were being populated and not just the ones the user had permissions to. Therefore, this change involves looking up metadata from internal system tables instead, respecting user access privileges.
=> Modified JDBC connectors to fetch metadata from underlying system tables.

athena-gcs/assembly.xml
After updating to Arrow 13, the athena-gcs JAR failed to publish due to increase in size. This change adds filter to exclude certain files during compilation.
=> Excluding large Mac/Windows Statically compiled files

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandler.java
DocDB skip collections that user has no permission to access by using mongoDB command line to retrieve collection names
https://github.com/awslabs/aws-athena-query-federation/issues/506
=> DocDB skip collections that user has no permission

.github/workflows/run_release_tests.yml, validation_testing/README.md, validation_testing/cdk_federation_infra_provisioning/app/lib/app.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/dynamo-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/opensearch-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/stack-props.ts, validation_testing/cleanup.sh, validation_testing/deploy_infra.sh, validation_testing/main.py, validation_testing/run_glue.sh, validation_testing/run_release_tests.sh, validation_testing/run_tests.sh, validation_testing/scripts/exec_release_test_queries.py
Added redshift and postgresql complex predicate tests. Refactored code for ease of local development setup.
=> Validation testing integrations

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandlerTest.java, athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandler.java, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandlerTest.java, validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/mysql_create_case_insensitive_data.py, validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/postgresql_create_case_insensitive_data.py, validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/redshift.py, validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/redshift_create_case_insensitive_data.py, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts, validation_testing/scripts/exec_release_test_queries.py
Add MySQL, PostgreSQL, and Redshift case insensitive schema functionality and requirements for validation testing.
Allow users to query MySQL, PostgreSQL, and Redshift tables with mixed cases. Also, added tests under validation_testing
=> Add case insensitive schema functionality

athena-cloudwatch/athena-cloudwatch.yaml, athena-dynamodb/athena-dynamodb.yaml
https://github.com/awslabs/aws-athena-query-federation/issues/1569
Add missing condition check in yaml files.
Tested both cases (with kms + lambda role and with kms key only).
KMS Key + LambdaRole creates no role or policy (Does nothing with key. Assumed that customer defines key policy in his own passed LambdaRole)
KMS Key creates role and policy
=> Add missing check to template with KMS keys

pom.xml
This commit temporarily disables doclint so that we can fix our javadocs at a later time. java11+ and maven javadoc added a very strict doc linter and it fails to allow javadocs to get created.
=> ignore doclint until we can fix at a later time

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandler.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandlerTest.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchMetadataHandlerTest.java
Implement pagination with document db
Remove unnecessary logs
Refactor DocDbMetadataHandlerTest to work with only doListTablesWithCommand
=> Implement docdb pagination

athena-federation-sdk/pom.xml, athena-hbase/pom.xml, athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaMetadataHandler.java, pom.xml
Netty has been directly chosen as a direct dependency for Federation Repo whereas its never used directly by any code-base (except one util class that got replaces accordingly).
Most importantly; the depend-bot has been upgrading Netty; which is core to `arrow` functionality, and recently we have upgraded to latest version which caused our SDK to fail.
This change removes the burden of deciding which Netty to choose; and let the transitive dependency be resolve by the direct dependency (in this case Arrow). 
I've ran unit-tests locally; and everything looks fine; however I recommend that we run integration tests; I'll run them on my fork afterwards. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> Remove direct dependency of Netty

validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/package.json
L2 construct has issues with creating the proper parameter group names under the hood.
=> Change L2 redshift construct to L1

.github/workflows/run_release_tests.yml
Remove explicit use of AWS Creds in Release Tests --  and run nightly release tests
This will allow us to automate the release tests; and nightly run them without having to need to manually provide credentials. 
I've ran this in my fork: https://github.com/AbdulR3hman/aws-athena-query-federation/actions/runs/7497336794/job/20410772814 successfully. Will run another release tests as soon as this PR merged (it should also run by itself every night at midnight)
=> Remove explicit use of AWS Creds in Release Tests -- 

.github/workflows/run_release_tests.yml
Three things changes:
1. Increase assume role that is needed for integ release tests as its currently timing out.
2. Reduce Maven logging level to WARN; this will help a lot when viewing action log; currently the build step generates over 40k of lines of logs.
3. Mute download dependencies entirely.
=> Reducing Maven Logging level; and increase Assume Role timeout

.gitignore, validation_testing/main.py, validation_testing/run_cleanup_infra.sh
These changes will ensure that we clean up anything that left as a residue from previous runs; we have been experiencing some resources that are not detaching or deleting in timely manner that would results in the entire stack failing.
Given we switched to daily run for our tests; this will give plenty of time by the next run for the resources to detach correctly; then clean up those resources then the stack. Before starting a new release tests. 
I've tested locally;
=> Adding extra cleanup procedures before executing release tests 

athena-snowflake/assembly.xml, athena-snowflake/athena-snowflake.yaml, athena-snowflake/pom.xml
Issue #, if available:
Snowflake Package Is Oversized
Description of changes:
Updated code to use assembly plugin.
=> snowflake package size issue fix

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/helpers/FieldsGenerator.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java
Support map with complex types as values.
Enabled map support that uses arrow changes (Refer to https://github.com/awslabs/aws-athena-query-federation/issues/361#issuecomment-1546547216)
=> Support map of complex types

athena-snowflake/athena-snowflake.yaml
Update the snowflake cfn template so that the connector does not need to be within a VPC. Changes modeled from the elasticsearch connector, which has the optional VPC connection.
=> make vpc optional in snowflake template

.github/workflows/publish_to_maven_central.yml
This will allow us to deploy `athena-jdbc` and `athena-mysql` to maven central. 
=> Deploy Mysql and JDBC Connectors to Maven Central

athena-datalakegen2/athena-datalakegen2.yaml, athena-google-bigquery/athena-google-bigquery.yaml, athena-hortonworks-hive/athena-hortonworks-hive.yaml, athena-oracle/athena-oracle.yaml, athena-saphana/athena-saphana.yaml, athena-snowflake/athena-snowflake.yaml, athena-sqlserver/athena-sqlserver.yaml, athena-synapse/athena-synapse.yaml, athena-teradata/athena-teradata.yaml
Change the following connectors to not require a VPC:
- Azure Datalake Gen2
- HortonWorks Hive
- Oracle DB
- SAP HANA
- Azure SQLServer
- Synapse
- Teradata
The change to the template for each of these was modeled off of the Google BigQuery connector template.
=> Make VPC optional in multiple connectors

.github/workflows/auto-approve.yml
This reverts commit ba03937623a57a43d94b9cbad4ef5503eabecb80.
We've temporarily disable dependBot auto merge of minor dependency version. this change will re-enable it. 
=> Revert "Disabled Automerge DependBot PRs Temporarily (#1789)"

athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryRecordHandler.java
https://github.com/awslabs/aws-athena-query-federation/issues/1767
observed that it's happening when the limit value is greater than the record count. placed the condition.
=> [BUG] error occurs when using the LIMIT clause with AthenaGoogleBigQueryConnector

athena-google-bigquery/pom.xml
Athena Bigquery connector dependency google-cloud-bigquery update issue.
updated google-cloud-bigquery to 2.37.0 and added grpc-api version 1.61.0 to maintain latest transitive dependecy.
=> BUG 1728 : pom changes for bigquery connector

athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamMetadataHandler.java, athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandler.java, athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/qpt/TimestreamQueryPassthrough.java
This will allow customer to pushdown the entire sql query down to the timestream database.
Syntax:
SELECT * FROM TABLE(system.query('<select * from \"databasename\".\"tablename\">'));
=> Extended QPT to athena-timestream

athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400MetadataHandler.java, athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400RecordHandler.java
Will allow customer to execute QPT on top of db2-as400
=> Extended QPT to athena-db2-as400

athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseConstants.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseDataType.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandler.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseRecordHandler.java
Will allow customer to execute QPT on top of Synapse
=> Extended QPT to athena-Synapse

validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts
Aurora mysql version VER_3_01_0 was no longer supported so release tests would fail. Upgraded this version so the proper rds instance can be deployed.
=> Upgrade mysql version

athena-redis/athena-redis.yaml, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandler.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisRecordHandler.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/lettuce/RedisCommandsWrapper.java, athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/qpt/RedisQueryPassthrough.java
Query Passthrough changes for the Redis connector. Works by taking in 3 arguments, the script, keys, and argv. The script is a lua script passed as a string. The keys and argv arguments are strings representing arrays of additional arguments for the script. These three arguments are then passed to the Lettuce client eval_ro command. See the [redis Lua scripting documentation](https://redis.io/docs/latest/develop/interact/programmability/eval-intro/) for more details.
Because query passthrough works by running Lua scripts, query passthrough may not work for clustered instances due to the limitations around a Redis Lua script accessing data from multiple hashes.
Additionally adds 4 additional lambda environment variables for storing QPT connection information since …
=> Query Passthrough for Redis Connector

athena-redshift/pom.xml
Fixes #1944. Fixes a NoClassDefFoundError that is thrown by some features that are looking for classes in the Redshift Serverless SDK.
*Issue #:* #1944 
*Description of changes:* Added aws-java-sdk-redshiftserverless to the dependency list for athena-redshift
=> Add Redshift Serverless SDK

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcMetadataHandler.java
QPT was not working with Mutli-plexed connector; this is due to the missing logic in the `MultiplexingJdbcMetadataHandler` class.
Added logic for the QPT get schema method in the `MultiplexingJdbcMetadataHandler` class.
=> Extended QPT to JDBC Multiplexing

athena-neptune/pom.xml, athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/NeptuneConnection.java, athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/propertygraph/NeptuneGremlinConnection.java, athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/propertygraph/rowwriters/CustomSchemaRowWriter.java
#1574
The SigV4 library used for IAM in Gremlin connection in Neptune connector is a deprecated library, this PR updates it to use the new maintained library for signing. The deprecated library is only recommended to be used with 3.4.x Gremlin drivers, and may work when using 3.5.x and earlier 3.6.x driver versions, but will no longer work with 3.7.x.
Also downgraded the Gremlin driver version used by the connector to within the supported range for Neptune (currently 3.6.5 is the max). 
I was able to reproduce the error on 3.7.1 gremlin console, trying to connect to IAM enabled cluster using the old SigV4 signing library:
I have tested the fix in this PR by deploying a customer connector and querying an IAM enabled cluster, and was …
=> Updated SigV4 signing library in Gremlin connection for Neptune connector

tools/prepare_dev_env.sh
When setting up an environment recently, was using the prepare_dev_env.sh script and noticed it had not been updated; the maven version fetched was not new enough for building and the recommended instruction for amazon linux was not updated for Amazon Linux 2023. Updated to maven 3.9.6 and added a note for Amazon Linux 2023 compatible command.
=> Updated prepare_dev_env.sh script

athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/query/PredicateBuilder.java, athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/query/SelectQueryBuilderTest.java
This PR fixes #1887.
This PR adds the conversion from `TIMESTAMP`/`DATE` types to Timestream's `TIMESTAMP` type to fix `ValidationException`.
=> Fix ValidationException for Timestream connector

athena-kafka/athena-kafka.yaml, athena-kafka/pom.xml, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/GlueRegistryReader.java, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaConstants.java, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaMetadataHandler.java, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaRecordHandler.java, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaUtils.java, athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/dto/AvroTopicSchema.java, athena-kafka/src/test/java/com/amazonaws/athena/connectors/kafka/KafkaMetadataHandlerTest.java, athena-kafka/src/test/java/com/amazonaws/athena/connectors/kafka/KafkaRecordHandlerTest.java, athena-kafka/src/test/java/com/amazonaws/athena/connectors/kafka/KafkaUtilsTest.java
Support for querying Avro Data from Kafka.
Prerequisite: Define the Avro Schema in AWS Glue Schema Registry, Use Data Format as AVRO.
Note: Provide Glue Schema Name as Kafka Topic Name with same case .
example avro schema in glue :
```
{
"type": "record",
"name": "employee",
"fields": [
{
"name": "id",
"type": "int"
},
{
"name": "name",
"type": "string"
}
]
}
```
=> [FEATURE] Add Support for querying Avro Data in Kafka Connector

athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/HbaseConnectionFactory.java, athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/HbaseKerberosUtils.java, athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/connection/HbaseConnectionFactory.java, athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/integ/HbaseTableUtils.java, athena-hbase/src/main/resources/core-site.xml, athena-hbase/src/main/resources/hbase-site.xml
Currently the default authentication is Kerberos for HBase. We made changes to allow both authentications (with or without Kerberos). We have tested HBase with both kerberos setup and without kerberos setup, it's working fine.
=> Added changes to support without kerberos authentication

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java, athena-postgresql/pom.xml, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlQueryStringBuilder.java, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandlerTest.java, athena-redshift/pom.xml, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandlerTest.java
[ [BUG] Redshift 'char' column constraint pushdown does not work #62 ](https://github.com/awslabs/aws-athena-query-federation/issues/62)
PostgreSQL/Redshift database will send data along with trailing whitespaces in CHAR datatype columns. So, removed those spaces using the RTRIM() function while building the SQL query.
=> [Fix] Remove Trailing Whitespaces from Char Column in Postgresql/Redshift Connector

athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandler.java, athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryRecordHandler.java, athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryUtils.java
[BigQueryIssue.docx](https://github.com/user-attachments/files/16085413/BigQueryIssue.docx)
Issue 1: Select count(*) on empty table returns a java exception
Details - They ran a query - SELECT COUNT(*) FROM SOME_EMPTY_TABLE_IN_BIG_QUERY caused a Java ILLEGALSTATEEXCEPTION
Issue 2: Connector does not update the case of projectId
If table doesn't have any data, then we are throwing IllegalStateException. This issue is fixed with these changes, If table doesn't have any data, we will return zero and I have attached the test results as well. 
And projectId casing issue also fixed in this PR, as per official documentation big query projectId should contain only lowercase letters, numbers, and hyphens. So, we are converting projectId to …
=> BigQuery empty table and projectId casing issues fix

athena-neptune/pom.xml, athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/rdf/NeptuneSparqlConnection.java
dependency bot upgrade rdf4j-repository-sparql 3.7.7 to 5.0.1
After upgradation, encountered compilation errors. 
As suggested in doc., used IRI instead. removed URI part.
=> Neptune dependency upgrade

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/QueryUtils.java, athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/QueryUtilsTest.java
https://github.com/awslabs/aws-athena-query-federation/issues/507 
Converting String to ObjectId when querying using _id column in docdb.
In DocumentDB _id column data type is ObjectId when we query with _id as String it won't return any results so converting String to ObjectId will return results. PFA testing doc for the same.
[DocumentDB test with _id.docx](https://github.com/user-attachments/files/16233803/DocumentDB.test.with._id.docx)
=> DocDB select query with _id issue fix

athena-msk/pom.xml, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskConstants.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandler.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskRecordHandler.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskUtils.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/GlueRegistryReader.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/BaseMskConsumer.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/MskAvroConsumer.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/MskConsumer.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/MskDefaultConsumer.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/MskProtobufConsumer.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/MskRecordProcessor.java, athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/dto/AvroTopicSchema.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandlerTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskRecordHandlerTest.java, athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskUtilsTest.java
Support for querying Avro and Protobuf data from Amazon MSK.
Prerequisite: Define the Avro/Protobuf Schema in AWS Glue Schema Registry, select Data Format as Avro/Protocol Buffers while defining schema.
Note: Provide Glue Schema Name as MSK Topic Name with same case.
Example avro/protobuf schema in glue :
```
Avro:
{
"type": "record",
"namespace": "ABC_Organization",
"name": "Employee",
"fields": [
{
"name": "Name",
"type": "string"
},
{
"name": "Age",
"type": "int"
},
{
"name": "IsActive",
"type": "boolean"
},
{
"name": "Balance",
"type": "double"
},
{
"name": "Rating",
"type": "float"
}
]
}
Protobuf:
message protobuftest {
optional string name = 1;
optional int64 calories = 2;
optional string colour = 3;
optional bool isOrganic = 4;
optional double price = 5;
optional float weight = 6; …
```
=> [FEATURE] Add Support for querying Avro/Protobuf Data in athena-msk Connector

athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/TPCDSMetadataHandler.java, athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/TPCDSRecordHandler.java, athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/TPCDSUtils.java, athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/qpt/TPCDSQueryPassthrough.java
Enabled QPT support for TPCDS Connector; this is connector is not for production use; neither the implementation of this QPT.
Allow's execution of QPT as follow:
```
SELECT * FROM TABLE(
system.query(
TPCDS_CATALOG => 'tpcds', 
TPCDS_SCHEMA => 'tpcds250', 
TPCDS_TABLE => 'call_center'
)
);
```
=> Added QPT Support for TPCDS Connector

athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsMetadataHandler.java, athena-cloudwatch-metrics/src/test/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsMetadataHandlerTest.java
When using this connector I noticed that some of my queries on highly-dimensional namespaces returned zero results.  The root cause it that if no MetricStats are produced in the first ListMetrics page (the constraints don't match), then the connector would return no splits *and no continuation token even if there is one*.  This change fixes that bug by returning the continuation token so that GetSplits gets called again. And I updated a unit test to verify.
=> Fix for cloudwatch-metrics pagination bug

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java
athena-sqlserver connector is unable to list views on athena console.
'sys.tables' system view can only list tables in SQL Server. So, changed to 'sys.objects' which can list both tables and views.
=> [Fix] Add views to the Table list in athena-sqlserver connector

athena-db2-as400/athena-db2-as400.yaml, athena-db2/athena-db2.yaml
Makes VPC optional for db2 connectors. Mimics how it was done for other connectors: https://github.com/awslabs/aws-athena-query-federation/pull/1794
=> Make VPC optional in DB2 connectors

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java
#1306 SQL Server Connector expects Dbo (i.e ROOT) privilege work - it lists only the databases created by user who is issqluser, Most prod deployment have DB created by user which is not issqluser
Updated the list schema query to now fetch all user-defined schemas.
=> sqlserver connector listSchema query changes

athena-vertica/pom.xml, athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaCompositeHandler.java, athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaConstants.java, athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaSchemaUtils.java
While testing v2 migration changes for Vertica connector we found that it's failing to get ArrowReader object.
The issue is with getting ArrowReader from constructArrowReader() function, it seems if we want to get datasetFactory object it requires cacerts and ssl cert to be set native environment variables. Similar functionality we have seen in GCS connector and implemented same in Vertica, after that it's working fine. Please find attached logs for more details on error. 
Added changes to fix this issue.
[v2-vertica-error-logs.txt](https://github.com/user-attachments/files/16686245/v2-vertica-error-logs.txt)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> v2 migration vertica issue fix

athena-cloudwatch/pom.xml, athena-elasticsearch/pom.xml, athena-federation-integ-test/pom.xml, athena-federation-sdk/pom.xml, athena-jdbc/pom.xml, athena-redis/pom.xml, pom.xml
- Don't declare jsii-runtime as a dependency of any component directly
this direct dependency that was added to some modules is a transitive
dependency of the cdk packages that are used just for testing.
The original intent of adding jsii-runtime as a dependency was to just
exclude the jackson version that are dependencies of it.
The scope of the dependency was missing when it should be
<scope>test</scope> which cause the dependency to be included in the
final jar of the connectors.
Instead I declare it in the top-level dependency management with its
exclusions so the dependency scope is unchanged
- The test scope tag was also missing on a cdk dependency of the cloudwatch connector
=> Don't declare jsii-runtime as a dependency of any component directly

athena-cloudwatch-metrics/pom.xml, athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricStatSerDe.java, athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricUtils.java, athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsExceptionFilter.java, athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsMetadataHandler.java, athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsRecordHandler.java, athena-cloudwatch-metrics/src/test/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricStatSerDeTest.java, athena-cloudwatch-metrics/src/test/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricUtilsTest.java, athena-cloudwatch-metrics/src/test/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsMetadataHandlerTest.java, athena-cloudwatch-metrics/src/test/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsRecordHandlerTest.java
Part of https://github.com/awslabs/aws-athena-query-federation/issues/2088
Migrate the cloudwatch metrics connector to AWS SDK v2.
Significant change: Changed serialization/deserialization for `MetricStatSerDe.java`. Previously, the `MetricStat` class had getters and setters which Jackson used for serialization and a `MetricStatHolder` was used to hold this. Now got rid of the `MetricStatHolder` class. Serialize by converting to `MetricStat` builders. Then Deserialize using a Jackson `CollectionType` made with the class returned by `MetricStat.serializableBuilderClass()`, and convert the returned list of `MetricStat` builders to a list of `MetricStat`s.
Referenced https://stackoverflow.com/questions/34176607/custom-deserialization-of-list-using-jackson
By …
=> Migrate Cloudwatch Metrics connector to v2

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlQueryStringBuilder.java, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandler.java, athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandlerTest.java, athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandler.java, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandlerTest.java, athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaQueryStringBuilder.java
Postgresql default collate setting differs from Athena's and thus causes issues that results of missing records; for example:   PostgreSQL `'a' < 'A'` &  Trino `'A' < 'a'`. This causes the dynamic filtering range to miss records. 
This change will allow customers to enforce `Collate "C"` to any `varchar` based predicate. 
**warning**: this is only an experimental feature. 
=> Collate Aware Postgresql String Builder

athena-redis/pom.xml, athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/integ/RedisIntegTest.java
https://github.com/awslabs/aws-athena-query-federation/issues/2093
Migrate Elasticache to AWS SDK v2. It is only used in integration tests of athena-redis connector.
=> Migrate Elasticache to AWS SDK v2

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/exceptions/AthenaConnectorException.java
This is to classify the RuntimeException in each athena connector to be more specific, including a error message and a error code. The plan is to re-use the FederationSourceErrorCode and ErrorDetails from com.amazonaws.services.glue.model
=> Add athena connector exception class to classify Runtime Exception

athena-jdbc/pom.xml, athena-redshift/pom.xml, athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/integ/RedshiftIntegTest.java
#2089 SDK V2 changes for redshift
SDK V2 changes for redshift
removed redshift serverless dependency from redshift pom as it is not in use.
removed redshift dependency from Athena-jdbc as it is not in use.
=> v2 sdk changes redshift

athena-cloudwatch/pom.xml, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchExceptionFilter.java, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchMetadataHandler.java, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchRecordHandler.java, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchTableResolver.java, athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchUtils.java, athena-cloudwatch/src/test/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchMetadataHandlerTest.java, athena-cloudwatch/src/test/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchRecordHandlerTest.java, athena-cloudwatch/src/test/java/com/amazonaws/athena/connectors/cloudwatch/integ/CloudwatchIntegTest.java
*Issue #, if available: https://github.com/awslabs/aws-athena-query-federation/issues/2088*
Migrate the cloudwatch connector to AWS SDK v2.
AwsLogs renamed to CloudwatchLogs from v1 to v2.
=> migrate awslogs to cloudwatchlogs (v1 to v2)

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleRecordHandlerTest.java
Customer has complained that in Oracle DB RDS they are seeing different date (offset by 1) for any dates prior to 1/1/1970. 
**Example**: 
• Database stores 7/20/1967 
o SQL*Plus query: 7/20/1967 
o Athena query: 7/21/1967 
• Database stores 7/20/1972 
o SQL*Plus query: 7/20/1972 
o Athena query: 7/20/1972
This code changes resolves the issue and now we will see correct dates. Please refer attached doc for more details and testing results.
[Oracle Date Type Issue Testin2.docx](https://github.com/user-attachments/files/17115900/Oracle.Date.Type.Issue.Testin2.docx)
=> Oracle date issue fix

.github/workflows/javadoc_sync.yaml
The original script was pointing to the wrong path;
according to documentations: https://maven.apache.org/plugins/maven-javadoc-plugin/aggregate-mojo.html
the Default location is ${project.build.directory}/reports
=> Java Docs were github action was pointing to wrong directory

athena-teradata/athena-teradata.yaml, athena-teradata/pom.xml
Image-based lambda cannot have layer properties. Remove the need for the teradata layer by adding teradata jdbc as a dependency instead. Now with ECR, jar/dependency size is not an issue so this can be done.
=> Fix teradata

athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java, athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AWSRequestSigningApacheInterceptor.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsRestHighLevelClient.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsRestHighLevelClientFactory.java, athena-federation-sdk/pom.xml, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/credentials/CrossAccountCredentialsProvider.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtil.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/QueryStatusCheckerTest.java, athena-jdbc/pom.xml, athena-kafka/src/test/java/com/amazonaws/athena/connectors/kafka/KafkaUtilsTest.java, athena-msk/pom.xml, athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaMetadataHandler.java, pom.xml
https://github.com/awslabs/aws-athena-query-federation/issues/1960
Final few changes to fully remove the dependency on AWS SDK v1.
Key changes:
* com.amazonaws.util.json.Jackson was removed in v2, so ObjectMappers were used instead.
* AWSRequestSigningApacheInterceptor.java used many features no longer in v2. It was updated to use the new v2 features.
* CredentialsProviders updated to v2.
=> V2 final changes

athena-synapse/athena-synapse.yaml
=> [Fix] athena-synapse: Add missing s3 permissions to spill the data that exceeds lambda function limits

athena-google-bigquery/pom.xml
While migrating RDS service to AWS SDK V2, accidentally updated for cdk as well. So, reverting back to original code. 
=> reverting PR #2273 for gbq connector as it's not required for cdk.

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerQueryStringBuilder.java, athena-sqlserver/src/test/java/com/amazonaws/athena/connectors/sqlserver/SqlServerQueryStringBuilderTest.java
This change adds a null check for the partition function and partitioning column in Athena SQL Server connector. It ensures that data will be fetched using specific partition when the necessary partition information is available.
Note: customer's schema has not yet been verified.
=> [Fix] athena-sqlserver: Add null check for partition function and partitioning column in getPartitionWhereClauses method

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchSchemaUtils.java, athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchTypeUtils.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchTypeUtilsTest.java
https://github.com/awslabs/aws-athena-query-federation/issues/1611 Support geopoint data type for Elasticsearch.
To support geo_point type in elasticsearch we have few challenges in SDK side changes, so we are converting geo_point type to varchar and showing geo_point data in athena. Please find attached document for more detail analysis on this.
[Elasticsearch_geopoint_analysis.docx](https://github.com/user-attachments/files/16907035/Elasticsearch_geopoint_analysis.docx)
=> Elasticsearch geo_point type support by converting to varchar

.github/workflows/run_release_tests.yml, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/dynamo-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/opensearch-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts, validation_testing/deploy_infra.sh, validation_testing/main.py, validation_testing/run_release_tests.sh
Update the validation testing to deploy an ECR repository, build and push an image of the connector to the created repository, and update the template to point to the correct ImageUri.
=> update validation_testing to use ECR

athena-oracle/athena-oracle-connection.yaml
Oracle create data catalog failing due to kmskeyid being required by cloud formation. This is because it doesn't have a default.
=> add default to oracle connection kmskeyid

athena-db2/src/main/java/com/amazonaws/athena/connectors/db2/Db2EnvironmentProperties.java
While testing DB2 connector in the **panama-sdkv2-gdcv2** branch, encountered the following error:
Invalid database URL syntax : **jdbc:db2://host:port:databaseName?**
Expected URL format: **jdbc:db2://host:port/databaseName**
=> [panama-sdkv2-gdcv2] Fix Db2 JDBC Connection String

athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseEnvironmentProperties.java
While testing panama changes for synapse, we found an issue as "No suitable driver found". To address this issue, we have updated connection string prefix.
=> Synapse panama issue fix, updated connection string prefix.

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/connection/EnvironmentConstants.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleEnvironmentProperties.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java
Previously, no matter what, the same jdbc oracle url would be used. For SSL, a different oracle url is required, so SSL was not possible with a glue connection. Now, a check is added to see if the ENFORCE_SSL property is set.
=> update to use SSL oracle url

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java
Currently if a secret is used for username and password, if the password is not encased in double quotes, it will cause an error (this is documented in the oracle DB documentation). This change checks to make sure the password is not already inside of double quotes (to not break existing customers using double quotes). If it is not, it adds the double quotes.
=> add quotes around oracle password

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/connection/EnvironmentProperties.java
While testing Oracle connector in the panama-sdkv2-gdcv2 branch, encountered error because KMS_KEY_ID is necessary parameter required in connection string.
Code changes is done to remove condition check for KMS_KEY_ID.
=> [panama-sdkv2-gdcv2] Oracle Panama Testing Fix 

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java
Due to a merge conflict likely, it wasn't using the `password` variable that encases the password in double quotes.
=> fixing to use quoted password

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java
For some reason the `IS_FIPS_ENABLED` field was changed. In order to support both the old or new, we now check for either.
=> check legacy IS_FIPS_ENABLED

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java
- date: getting jdbc column type as date(millisecond) with scale 7, updated condition check.
- TIMESTAMP_WITH_TZ, TIMESTAMP_WITH_LOCAL_TZ: updated the condition check with jdbc column type.
- negative scale datatype :  added condition on negative scale. but not sure earlier implemented condition was used as converted datatype was BIGINT. so removed the code.
attached doc with screenshots and functional test document.
[ORACLE_FUNCTIONAL_TEST.xlsx](https://github.com/user-attachments/files/18061525/ORACLE_FUNCTIONAL_TEST.xlsx)
[Oracle_datatype_fix_test.docx](https://github.com/user-attachments/files/1 …
=> Converting Oracle unhandled datatypes to Arrow types

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandlerTest.java
Oracle handle was misahndling classifications of decimal types; there were also other unneeded loop to get the column fields in order to reclassify some types; which now is used through the column metadata handler.  
=> Oracle metadata decimal bug & Clean up

athena-oracle/Dockerfile, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java
Enabling RDS Certs for ECR based image; tested this on RDS Oracle with FIPS and SSL enabled: 
I've also simplified the logic to check if the connection string is using TCPS (Secure Transport) protocol instead of (TCP). 
=> Enabled RDS Certs for Oracle DB

athena-neptune/docs/neptune-connector-setup/README.md
=> Update neptune documentation

tools/bump_versions/common.py
The oracle Dockerfile had a new line added where the version number needs to be updated from 2022.47.1 to the version of the release. This was not added before to the update_dockerfile command, causing the building of the image to fail.
Update the update_dockerfile to now change all instances of `athena-*-2022.47.1.jar` to the correct version. This will make it so any changes made to any of the dockerfiles in the future will work and not cause a fail.
=> Update update_dockerfile to catch all version numbers used by jar

athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400EnvironmentProperties.java, athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandler.java, athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandler.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/JdbcEnvironmentProperties.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java
partially reverts commit https://github.com/awslabs/aws-athena-query-federation/commit/0ffb7b8bdd42032d7f8d42a5e36300b68a87f37a.
=> Revert various cleanup fixes (#2467)

athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaMetadataHandler.java
Issue #, if available:
Records mismatch for large datasets, such as 10M records.
The executeQueriesOnVertica method was being triggered multiple times due to multiple requests, leading to duplication issues.
Description of changes:
Added a conditional check to ensure that the executeQueriesOnVertica method is invoked only once per queryId. Tested with large datasets to confirm records match. Please find attached document.
[vertica-data-mismatch.odt](https://github.com/user-attachments/files/17900509/vertica-data-mismatch.odt)
=> Fix data mismatch issue in Vertica Connector

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolverTest.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandlerTest.java
Oracle by default upper cases everything. Glue does not support anything aside from lowercase. Originally, we were casing everything to upper case to match oracle. Now to support glue connections, we need to not do this. So we have three casing modes now, upper (default for legacy connectors), lower (default for connectors using glue connections), and now search, which will perform a case insensitive search.
=> Oracle case insensitive search

.github/workflows/auto-approve.yml
1. re-enable dependabot to auto merge minor versions (this was stopped when we were merging a large feature into master)
2. Make sure that the auto merge ignores preview/beta versions that are not supposed to be production ready. 
=> Enabled Auto Merge for minor version exluding preview/beta

README.md
Added Coverage Map to the Readme
=> Added CodeCoverage Map

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java
Sqlserver in the query editor always returns UPPERCASE table names even though if we created sqlserver tables with lowercase table names. This is because of we are always converting requested table name to UPPERCASE in doGetTable function. 
After removing this uppercase conversion then it's returning both lowercase and uppercase table names in the query editor.
=> Sqlserver in the query editor always returns UPPERCASE table names issue fix

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/qpt/DDBQueryPassthrough.java
Enhanced SQL statement validation to handle disallowed keywords appearing as substrings. Introduced regular expression-based word boundary matching to accurately detect whole-word occurrences of disallowed operations, preventing potential misinterpretations and unintended false positives.
#2323
- Modified the `customConnectorVerifications` method in the `DDBQueryPassthrough` class.
- Replaced the previous implementation that used a simple `contains` check to detect disallowed keywords.
- Introduced the use of regular expressions and the `java.util.regex.Matcher` class to perform word boundary matching.
- Added a regular expression pattern (`\\w+`) to match one or more word characters.
- Implemented a loop that iterates through all word …
=> Bug fix: Enhanced SQL statement validation with word boundary matching

athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaConstants.java, athena-saphana/src/test/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandlerTest.java
The Saphana Glue Get Table API was not retrieving data as expected due to a case-sensitivity issue with the PART_ID column. By converting the PART_ID column to lowercase, we achieved successful data retrieval through the Glue API.
=> Saphana glue get table api issue fix

athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataEnvironmentProperties.java, athena-teradata/src/test/java/com/amazonaws/athena/connectors/teradata/TeradataEnvironmentPropertiesTest.java
Issue #, if available:
The Teradata JDBC connection string requires a specific format to include the port number.
Example URL:
jdbc:teradata://host/TMODE=ANSI,CHARSET=UTF8,DATABASE=TEST,**DBS_PORT=1025**,user=dummy,password=dummy
Previously, the port was included in the connection string as host:port, which was not compatible with the Teradata JDBC driver
Description of changes:
Overridden the connectionPropertiesToEnvironment method to include the port number as a DBS_PORT parameter.
=> Add port  number as a DBS_PORT parameter in Teradata JDBC Connection String

pom.xml
https://github.com/awslabs/aws-athena-query-federation/issues/2510.
SQL Server, Synapse and Gen2 connectors are failing with the following error:
java.lang.StringIndexOutOfBoundsException: begin 0, end -6, length 10
at java.lang.String.checkBoundsBeginEnd(Unknown Source) ~[?:?]
at java.lang.String.substring(Unknown Source) ~[?:?]
at com.microsoft.sqlserver.jdbc.ConfigurableRetryLogic.getCurrentClassPath(ConfigurableRetryLogic.java:290) ~[task/:?]
This issue is caused by version upgrade of mssql-jdbc dependency which is in preview state.
Reverted to the previous version of the dependency.
=> Revert "bump com.microsoft.sqlserver:mssql-jdbc from 12.8.1.jre11 to 12.9.0.jre11-preview"

.github/dependabot.yml, athena-redshift/pom.xml
Dependabot automatically bumped the redshift version, which caused release tests to fail. Why is unknown. This has been reverted before (https://github.com/awslabs/aws-athena-query-federation/pull/2469), but now is added to dependabot ignore list.
=> Revert redshift version bump

validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts
Current tests are failing due to not being able to support version 13.7 for aurora-postgresql ; upgrading the cluster to use the latest version. 
=> Upgraded RDS Postgresql Version Used In Integ Tests

athena-cloudera-hive/src/main/java/com/amazonaws/athena/connectors/cloudera/ClouderaHiveEnvironmentProperties.java, athena-cloudera-hive/src/test/java/com/amazonaws/athena/connectors/cloudera/ClouderaHiveEnvironmentPropertiesTest.java
The connection string was not forming correctly, which caused an error.
Expected Connection string should be in "jdbc:hive2://50.100.100.000:49100/default;UID=username;PWD=pass" format but we were getting  "jdbc:hive2://50.100.100.000:49100/default?UID=username;PWD=pass".
After making these code changes, it is now successful. PFA test doc for LF testing with glue.
[CLOUDERA-HIVE_PH2.xlsx](https://github.com/user-attachments/files/18534323/CLOUDERA-HIVE_PH2.xlsx)
=> CLOUDERA-HIVE Connection String Fix

athena-cloudera-impala/src/main/java/com/amazonaws/athena/connectors/cloudera/ImpalaEnvironmentProperties.java, athena-cloudera-impala/src/test/java/com/amazonaws/athena/connectors/cloudera/ImpalaEnvironmentPropertiesTest.java
The connection string was not forming correctly, which caused an error. 
Expected Connection string should be in "jdbc:impala://50.100.00.00:49172/default;UID=username;PWD=pass"  format but we were getting in "jdbc:impala://50.000.00.00:49172/?UID=username;PWD=pass".
After making these code changes, it is now successful. PFA test doc for LF testing with glue.
[CLOUDERA_IMPALA_PHASE2.xlsx](https://github.com/user-attachments/files/18520945/CLOUDERA_IMPALA_PHASE2.xlsx)
=> CLOUDERA-IMPALA Connection String Fix

athena-jdbc/pom.xml, athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlQueryStringBuilder.java, pom.xml
Fixing `commons-logging` that brings in vulnerable `log4j` version 1; as well as excluding H2 database from `arrow-jdbc`. 
Please note that AWS Inspector will still show risk for the h2 database; this is due to how the service actually search for vulnerability using the pom; which as of now we can't upgrade above from arrow-jdbc 13; without upgrading everything else. However this should remove the H2 Jar all together from the final package. Moreover; it is a test dependency; so even then it shouldn't have brought it in.
=> Addressing CVE-2021-42392,CVE-2022-23221,CVE-2022-23305,CVE-2019-17571

athena-dynamodb/athena-dynamodb-package.yaml
Government regions do not support ECR deployment, so adding these templates back to be deployed there. Also useful for testing sometimes
=> add dynamodb package-based template back

athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsRecordHandler.java
Timestamp were truncated for CW Metrics; this fixes the issue
=> Fixed Timestamp truncation

validation_testing/cdk_federation_infra_provisioning/app/package.json
Update CDK CLI version to match aws-cdk-lib to resolve `This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 36.0.0, but found 39.0.0)`
=> Update aws-cdk cli version to match aws-cdk-lib 2.177.0

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/connection/EnvironmentProperties.java
Cleanup and remove endpoint that is not in use - This was part of initial development with connectors working with Glue Connection; currently all tests are by default pointing to production and this is was purely for internal development; 
=> Remove endpoint

pom.xml
All our current build have thousands of line of encoding warning making any github action that has a maven build extremely hard to read; this should fix it. 
Enforce encoding setting on the parent project properties; this is following [stack overflow suggestion](https://stackoverflow.com/questions/3017695/how-can-i-configure-encoding-in-maven/3018152#3018152)
=> Fixed Encoding Warning

athena-clickhouse/src/test/java/com/amazonaws/athena/connectors/clickhouse/ClickHouseMuxJdbcMetadataHandlerTest.java, athena-cloudera-hive/src/main/java/com/amazonaws/athena/connectors/cloudera/HiveMetadataHandler.java, athena-cloudera-impala/src/main/java/com/amazonaws/athena/connectors/cloudera/ImpalaMetadataHandler.java, athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandler.java, athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400MetadataHandler.java, athena-db2/src/main/java/com/amazonaws/athena/connectors/db2/Db2MetadataHandler.java, athena-google-bigquery/pom.xml, athena-hortonworks-hive/src/main/java/com/amazonaws/athena/connectors/hortonworks/HiveMetadataHandler.java, athena-jdbc/pom.xml, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcArrowTypeConverter.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcArrowTypeConverterTest.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java, athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandler.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java, athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandler.java, pom.xml
Upgrading to Arrow 18; this will move of from few CVEs as well as bring us closer to the latest version of arrow. requires further testing; release testing, etc. 
Most notable changes are:
* JdbcArrowTypeConverter returns an `Optional`; this helps readability and better than null checking 
* Excluding arrow packages that were conflicting from `google-big-query`; version 15 was coming instead of 18. This requires manual testing of `google-big-query`
=> Upgraded Arrow to 18

athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandlerTest.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcArrowTypeConverter.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcArrowTypeConverterTest.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java, athena-oracle/src/test/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandlerTest.java, athena-saphana/src/test/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandlerTest.java, athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java, athena-sqlserver/src/test/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandlerTest.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandlerTest.java
This PR includes changes for mapping TIMESTAMP_WITH_TIMEZONE (Java SQL type 2014) to the DATEMILLI Arrow type, along with the necessary test case updates.
=> Arrow upgrade timestamp with timezone support

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchMetadataHandler.java, athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchMetadataHandlerTest.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/DatabaseConnectionConfigBuilder.java
Adding `default` domain name when domain mapping missing from Glue connection, as Glue connection can contains only domain_endpoint.
=> improve ElasticSearch on handling domain_endpoint from Glue connection

.github/workflows/auto-approve.yml
Instead of merging all commits of `dependabot` to master as is; it is cleaner to squash merge; this commit will ensure that. 
=> Squash Dependabot commits instead of merge

athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2CaseInsensitiveResolver.java, athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandler.java, athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2CaseInsensitiveResolverTest.java, athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandlerTest.java
Unable to query external tables stored on ADLS Gen2 when case-sensitive collation is enabled.
1) Lowercased the partition number, as Glue supports only lowercase.
2) Added a new class Gen2CaseInsensitiveResolver to handle case sensitivity in schema/table lookups.
3) Added a configurable environment variable 'casing_mode', with the following options:
i) NONE (default):Uses the schema and table names provided by Athena Request without modification.
ii) CASE_INSENSITIVE_SEARCH: Adjusts schema and table names to match their actual stored values in the database.
Please find the attached test results.
[gen2-cs-collation-issue.odt](https://github.com/user-attachments/files/18905022/gen2-cs-collation-issue.odt) …
=> Add Support for Case-Insensitive Search in DataLake Gen2 Connector

athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseCaseInsensitiveResolver.java, athena-synapse/src/main/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandler.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseCaseInsensitiveResolverTest.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandlerTest.java
1) Invalid object name SYS.COLUMNS error occurs in Synapse Connector when case-sensitive collation is enabled.
2) Unable to query uppercase table names when case-sensitive collation is enabled.
1) Uppercase SYS.COLUMNS system view is not available in Synapse when case-sensitive collation is enabled. Changed it to lowercase sys.columns.
2) Added a method getExactCaseObjectName() which retrieves the exact schema and table name from Synapse instead of converting it to uppercase.
Please find attached functional test results.
[SYNAPSE_FUNCTIONAL_TEST_2025-02-18_10_47_47.742843.csv](https://github.com/user-attachments/files/18843005/SYNAPSE_FUNCTIONAL_TEST_2025-02-18_10_47_47.742843.csv) …
=> Fix Synapse Connector to Support Case-Sensitive Collation

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java
On Athena SQLServer was returning empty table list when Case Sensitive Collation is enabled at Database Level.
After making these code changes,it is working fine for different casing modes like 'UPPER', 'lower' and 'CASE_INSENSITIVE_SEARCH'.
=> Fix sqlserver casing mode

athena-clickhouse/src/main/java/com/amazonaws/athena/connectors/clickhouse/ClickHouseMetadataHandler.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandlerTest.java
1) java.sql.SQLException: Code: 60. DB::Exception: Table INFORMATION_SCHEMA.schemata doesn't exist. (UNKNOWN_TABLE) (version 22.2.2.1).
2) java.sql.SQLFeatureNotSupportedException: setAutoCommit = false not supported.
1) Fixed incorrect metadata queries for listing schemas.
2) Skipped setAutoCommit(false) and connection.commit() for ClickHouse, as ClickHouse operates in auto-commit mode and does not support transactions. Please find the attached test document.
[clickhouse-connector-issue.odt](https://github.com/user-attachments/files/19123988/clickhouse-connector-issue.odt)
=> Fix Metadata Queries and Skip setAutoCommit(false) and commit() for ClickHouse Connector

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeRecordHandler.java
error handling improvement changes for Athena Snowflake connector.
=> error handling changes for snowflake

athena-vertica/athena-vertica.yaml, athena-vertica/src/main/java/com/amazonaws/athena/connectors/vertica/VerticaMetadataHandler.java, athena-vertica/src/test/java/com/amazonaws/athena/connectors/vertica/VerticaMetadataHandlerTest.java
The Vertica connector previously required the export bucket parameter to be a bucket name only; folder paths were not supported. This change adds support for both bucket names and bucket names with folder paths.
Before fixing supported format: my_vertica_exportbucket.
After fixing supported format: my_vertica_exportbucket and my_vertica_exportbucket/vertica.
[Vertica Export Bucket Prefix Path Support Testing.docx](https://github.com/user-attachments/files/18961669/Vertica.Export.Bucket.Prefix.Path.Support.Testing.docx)
=> Vertica export bucket prefix path support implementation.

athena-docdb/Dockerfile, athena-oracle/Dockerfile
Docker build was failing due to version mismatches. Upgrading to openssl11 (OpenSSL 1.1) fixed the issues. Because we only use it for adding certs, no functionality should change between the previous version (OpenSSL 1.0.1) and the new.
=> update oracle and docdb dockerfiles to openssl11

athena-docdb/Dockerfile, athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBConnectionFactory.java, athena-oracle/Dockerfile, athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java
Enabling SSL for the Oracle connector resulted in a 'certificate path not found' error. This was resolved by using the default truststore. To maintain consistency, the same truststore configuration was applied to DocDB.
=> Updated rds truststore to default truststore for oracle and docdb.

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java
https://github.com/awslabs/aws-athena-query-federation/issues/2699
This PR fixes the issue that currently exists where query editor window does not load any tables if another table in the db is empty and instead shows an exception (as described in the bug https://github.com/awslabs/aws-athena-query-federation/issues/2699). Verified the fix in dev account.
Implemented the following changes -
- `athena-jdbc->JdbcMetadataHandler`: Removed the exception in getSchema call for when a table has no columns, instead added a log warning for it. Moved the partition schema updates to happen only for tables where columns exist since we're not exiting out of the call due to the exception anymore.
- `athena-jdbc->JdbcMetadataHandlerTest`: Updated the …
=> Removing exception on table with no columns during get table call

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/resolver/SnowflakeJDBCCaseResolver.java, athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java
Snowflake Connector missing pagination
Adding pagination for Snowflake Connector.
In JDBCMetadataHandler, moved the snippet: `String adjustedSchemaName = caseResolver.getAdjustedSchemaNameString(connection, listTablesRequest.getSchemaName(), configOptions);` inside the condition where pagination is not required. If pagination is required, the connector which overrides the method listPaginatedTables should appropriately use caseResolver to adjust the name of schema.
=> adding pagination for listTables for snowflake connector

validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts
Glue Jobs V1 are deprecated, upgrading them to V4
=> Upgrade Glue Job version to V4_0

athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandlerTest.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandlerTest.java
Adding Fake Pagination to default listPaginatedTables in jdbcMetadataHandler.
Every connector should have the method listPaginatedTables overridden and implemented since each connectors pagination logic. Some connectors don't have it overridden in which case the logic defaults to the method `listPaginatedTables` in jdbcMetadataHandler - which did not do any pagination.
We want to 'fake' pagination here. All tables are being pulled into memory, however, we will return a subset of those tables based on the nextToken and pageSize provided in the ListTablesRequest object to mimic the effects of pagination. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> adding fake pagination for fallback jdbc logic

athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandlerTest.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/util/PaginationHelper.java, athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/util/PaginationValidator.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/util/PaginationHelperTest.java, athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java, athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java, athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java, athena-synapse/src/test/java/com/amazonaws/athena/connectors/synapse/SynapseMetadataHandlerTest.java
added the case where start token is not null and pageSize can be unlimited size -- Added logic for common code related to pagination checks and 'fake' pagination where connectors can't support it. 
This is a continuation of the original change where we added pagination support to `doListTables` in Snowflake connector.  This change allows for the support of use case where pageSize is UNLIMITED_PAGE_SIZE (or -1) and the nextToken is something other than 0 or null.
We also have added a utility class to do basic checks across all our pagination. Making sure that pageSize is never less than -1 and also that token is never a negative number. If token is a really large number that exceeds the size of array of total tables, we will return an …
=> Feature to enhance pagination checks and abstraction

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java, athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsMetadataHandler.java, athena-gcs/src/test/java/com/amazonaws/athena/connectors/gcs/GcsMetadataHandlerTest.java
GCS Connector pagination is not implemented.
Added pagination for GCS connector and added logs for glue metadata handler.
=> Added pagination for GCS connector

athena-federation-sdk/pom.xml, pom.xml
Updating some dependency versions due to security vulnerabilities as listed below
- [CVE-2024-29857](https://nvd.nist.gov/vuln/detail/cve-2024-29857) - bouncy castle vulnerability, upgrading from 1.70 to 1.78
- [CVE-2024-7254](https://nvd.nist.gov/vuln/detail/cve-2024-7254) - protobuf vulnerability, upgrading from 3.25.3 to 3.25.5
did a `mv clean install` and it succeeded.
=> Updating versions of bouncy castle and protobuf

athena-aws-cmdb/pom.xml, athena-cloudwatch-metrics/pom.xml, athena-cloudwatch/pom.xml, athena-dynamodb/pom.xml, athena-jdbc/pom.xml, athena-mysql/pom.xml
https://github.com/awslabs/aws-athena-query-federation/actions/runs/15829841898/job/44622444072
Publishing to maven has been failing for new releases with the following errors, so added a fix for that
```
[INFO] Waiting until Deployment b15d810a-92dc-4490-9e37-163481d80fe0 is validated
Error:  
Deployment b15d810a-92dc-4490-9e37-163481d80fe0 failed
pkg:maven/com.amazonaws/athena-aws-cmdb@2025.25.1:
- Project name is missing
pkg:maven/com.amazonaws/athena-dynamodb@2025.25.1:
- Project name is missing
pkg:maven/com.amazonaws/athena-jdbc@2025.25.1:
- Project name is missing
pkg:maven/com.amazonaws/athena-mysql@2025.25.1:
- Project name is missing
pkg:maven/com.amazonaws/athena-cloudwatch@2025.25.1:
- Project name is missing …
```
=> Adding project name to connectors to fix maven failures

validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts, validation_testing/cdk_federation_infra_provisioning/app/package.json
https://github.com/awslabs/aws-athena-query-federation/actions/runs/15838247685/job/44646102243
Redshift has deprecated dc2 large node types which prevents creation of new clusters with dc2.large as the node type, so upgrading that to ra3.large as advised in the migration doc ([ref](https://w.amazon.com/bin/view/RedshiftDC2Deprecation/)).
*Testing:*
- Maven build succeeded 
- Validated the node type changes in local cdk.out as added below
```
"redshiftcluster5BDFFF97": {
"Type": "AWS::Redshift::Cluster",
"Properties": {
"AllowVersionUpgrade": true,
"AutomatedSnapshotRetentionPeriod": 1,
"ClusterParameterGroupName": {
"Ref": "redshiftclusterParameterGroup3FF70CEF"
},
"ClusterSubnetGroupName": {
"Ref": "redshiftclusterSubnets7A92E844"
}, …
```
=> Updating redshift cluster node type in release tests due to deprecation of dc2 large node type

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/ThrottlingInvoker.java, athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/ThrottlingInvokerTest.java
Fixing a bug in the ThrottlingInvoker where it is unable to parse double values for the decrease settings
Current code throws a NumberFormatException when using a non whole number. The default value for this setting is 0.5 and allowed values are between 0.001 and 1
This change allows the double value to be converted from the String and stored in the invoker settings
=> Correct config value parsing for decrease value to use double 

athena-elasticsearch/pom.xml
snakeyaml 1.26 has a critical CVE (CVE-2022-1471). This overrides the dependency pulled in by the elasticsearch client.
=> Update snakeyaml dependency to 2.0 to address vulnerability with 1.26

athena-hbase/pom.xml, athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/HbaseTableNameUtils.java, athena-hbase/src/test/java/com/amazonaws/athena/connectors/hbase/HbaseTableNameUtilsTest.java
When using custom namespaces (non-default) in HBase tables with the Athena connector, queries fail with the following error:
GENERIC_USER_ERROR: Encountered an exception[java.lang.IllegalArgumentException] from your LambdaFunction[arn:aws:lambda:us-east-2:891643345752:function:hbase2025] executed in context[retrieving meta-data] with message[Illegal character code:58, <:> at 7. User-space table qualifiers may only contain 'alphanumeric characters' and digits: test_ns:employees]
These changes will fix the issue and also added missing dependency for loggers. 
Please find below attached issue analysis and testing doc for reference.
[HBase Namespace issue analysis and testing.docx](https://github.com/user-attachments/files/22233569/HBase.Names …
=> Hbase namespace issue

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeCredentialsProvider.java, athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/utils/SnowflakeAuthUtils.java
Addressing appsec review where error messages were potentially leaking info
=> Fixing error messages to not leak sensitive info
