athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-example/athena-example.yaml
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-redis/athena-redis.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
pom.xml

*Description of changes:* Marking 2020.04.1 Release

2020.04.1 Release

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-example/athena-example.yaml
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-redis/athena-redis.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
pom.xml

*Description of changes:* Updating version for new working copy

Updating version for new working copy

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question---how-tos.md

Updating issue templates to include general questions as well as enhancements

Update issue templates

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java
athena-redis/src/main/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandler.java
athena-redis/src/test/java/com/amazonaws/athena/connectors/redis/RedisMetadataHandlerTest.java

*Issue #, if available:* #108
Improving exception messages for Redis connector

[FEATURE 108] Improving exception messages for Redis connector

---

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/connection/GenericJdbcConnectionFactory.java

removing log of connection string

---

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBFieldResolver.java
athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandlerTest.java

https://github.com/awslabs/aws-athena-query-federation/issues/137
*Testing:*
Unit test

Fixing List type in a Document for docdb connector

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java

passing in required columns to dynamodb query/scan

passing in required columns to dynamodb query/scan

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-example/athena-example.yaml
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-redis/athena-redis.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
pom.xml

2020.17.1 Release

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java

https://github.com/awslabs/aws-athena-query-federation/issues/155
fixing bug with projection expression in dynamodb connector

fixing bug with projection expression in dynamodb connector

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-example/athena-example.yaml
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-redis/athena-redis.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
pom.xml

2020.19.1 Release

---

athena-federation-sdk/README.md

Correct typo in README.md

---

athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandlerTest.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/FieldResolver.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java

[#166] Fixes NPE when attempting to read/write NULL value for a List field within a Struct

[#166] Fixes NPE when attempting to read/write NULL value for a List field within a Struct

---

athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java

*Issue #, if available:* #175 
Removing incorrect import and dependency on javax

Removing incorrect import and dependency on javax

---

athena-elasticsearch/README.md
athena-elasticsearch/athena-elasticsearch.yaml
athena-elasticsearch/pom.xml

#77 #180
Set REST client API version to 7.0

Elasticsearch REST client API version

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-elasticsearch/athena-elasticsearch.yaml
athena-example/athena-example.yaml
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-redis/athena-redis.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
pom.xml

2020.33.1 Release

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/TestBase.java

*Issue #, if available:*  #248 #115 
*Description of changes:* Fixed data conversion from DDB Numeric to Arrow type including nested structures and nested arrays Closes #248 #115 

Fixed data conversion from DDB Numeric to Arrow type. Closes #248 #115

---

athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/GremlinQueryPreProcessor.java
athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/NeptuneRecordHandler.java
athena-neptune/src/test/java/com/amazonaws/athena/connectors/neptune/NeptuneRecordHandlerTest.java

bug fix for >= constraint and updates for =, != constraints

Athena to Neptune Connector: bug fix for >= constraint and updates for =, != constraints

---

athena-jdbc/README.md

Update readme file of athena-jdbc and add an example for the Jdbc connection string

Add example for the Jdbc connection string

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-aws-cmdb/pom.xml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch-metrics/pom.xml
athena-cloudwatch/athena-cloudwatch.yaml
athena-cloudwatch/pom.xml
athena-docdb/athena-docdb.yaml
athena-docdb/pom.xml
athena-dynamodb/athena-dynamodb.yaml
athena-dynamodb/pom.xml
athena-elasticsearch/athena-elasticsearch.yaml
athena-elasticsearch/pom.xml
athena-example/athena-example.yaml
athena-example/pom.xml
athena-federation-sdk-tools/pom.xml
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-hbase/pom.xml
athena-jdbc/athena-jdbc.yaml
athena-jdbc/pom.xml
athena-redis/athena-redis.yaml
athena-redis/pom.xml
athena-timestream/athena-timestream.yaml
athena-tpcds/athena-tpcds.yaml
athena-tpcds/pom.xml
athena-udfs/athena-udfs.yaml
athena-udfs/pom.xml
pom.xml

cutting release

---

athena-federation-sdk-tools/README.md
athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/IntegrationTestBase.java
athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/README.md

Fixes documentation typos for the Integration-Test Suite.

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandlerTest.java

QoL improvement - if a comment is all whitespace, don't add it to the metadata. 

Ignore empty comments and add unit test

---

athena-hbase/README.md
athena-hbase/etc/test-config.json
athena-hbase/pom.xml
athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/integ/HbaseIntegTestHandler.java
athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/integ/HbaseRowBuilder.java
athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/integ/HbaseTableUtils.java
athena-hbase/src/test/java/com/amazonaws/athena/connectors/hbase/integ/HbaseIntegTest.java

Added integration tests to the HBase connector.

HBase Integration Tests

---

athena-udfs/README.md

Updating syntax for UDF's

---

athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/splits/IntegerSplitter.java
athena-jdbc/src/test/java/com/amazonaws/connectors/athena/jdbc/splits/IntegerSplitterTest.java

*Issue #409*
Fix for the connector being stuck in scenarios where the min and max while splitting are the same.

Fix for issue-409

---

athena-aws-cmdb/pom.xml
athena-cloudwatch-metrics/pom.xml
athena-cloudwatch/pom.xml
athena-docdb/pom.xml
athena-dynamodb/pom.xml
athena-elasticsearch/pom.xml
athena-example/pom.xml
athena-federation-integ-test/pom.xml
athena-federation-sdk-tools/pom.xml
athena-federation-sdk/pom.xml
athena-hbase/pom.xml
athena-jdbc/pom.xml
athena-neptune/pom.xml
athena-redis/pom.xml
athena-timestream/pom.xml
athena-tpcds/pom.xml
athena-udfs/pom.xml
athena-vertica/pom.xml
pom.xml

Log4j refactor

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-elasticsearch/athena-elasticsearch.yaml
athena-example/athena-example.yaml
athena-federation-integ-test/README.md
athena-federation-sdk/athena-federation-sdk.yaml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-neptune/athena-neptune.yaml
athena-redis/athena-redis.yaml
athena-timestream/athena-timestream.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
athena-vertica/athena-vertica.yaml
pom.xml

Fix semantic version of 2022.2.1 release

Fix semantic version of 2022.2.1 release

---

.github/workflows/javadoc_sync.yaml
.github/workflows/maven_push.yml
.github/workflows/publish_to_maven_central.yml
athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-elasticsearch/athena-elasticsearch.yaml
athena-elasticsearch/etc/test-config.json
athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchTypeUtilsTest.java
athena-example/athena-example.yaml
athena-federation-integ-test/src/main/java/com/amazonaws/athena/connector/integ/stacks/ConnectorStack.java
athena-federation-sdk/athena-federation-sdk.yaml
athena-federation-sdk/pom.xml
athena-hbase/athena-hbase.yaml
athena-jdbc/athena-jdbc.yaml
athena-neptune/athena-neptune.yaml
athena-redis/athena-redis.yaml
athena-redis/pom.xml
athena-timestream/athena-timestream.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
athena-vertica/athena-vertica.yaml
pom.xml
tools/prepare_dev_env.sh

- Updated connectors to java 11
- Fixed elasticsearch integ test config file, and one of its unit tests
- Fixed the handler in timestream yaml file
- Updated prepare_dev_env.sh to java 11
- Updated Github Actions to java 11

Update to java11

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java

Its possible for `readWithConstraint` to read and spill data at a rate faster than the spiller leading to  query failures with `RejectedExecutionException`. The spill queue is currently fixed to size 2, and this pr will keep that default size of 2 while also giving the option of any other integer value.

Add adjustable spill queue

---

athena-cloudwatch-metrics/src/main/java/com/amazonaws/athena/connectors/cloudwatch/metrics/MetricsRecordHandler.java

fixes issue #658 
DIMENSION_VALUE_FIELD field was taking DIMENSION_NAME_FIELD to create a constraint for dimension value filed which was resulting in 0 results. Corrected that, now DIMENSION_VALUE_FIELD is used to create the required constraint.

Corrected the filter for DIMENSION_VALUE_FIELD

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java

Queries that have fast producers may be able to spill faster than the amount of time it takes to spill to S3. In this case, the query fails as below:
```
GENERIC_USER_ERROR: Encountered an exception[java.util.concurrent.RejectedExecutionException] from your LambdaFunction[arn:aws:lambda:us-east-1:373919111989:function:dynamo] executed in 
context[S3SpillLocation{bucket='burhan-test', key='athena-spill/c369cc8e-5379-4d5b-8cb1-7e71b763ad2c/34e58ca1-4ad5-4e53-acfe-40277b464d11', directory=true}] 
with message[Task java.util.concurrent.FutureTask@376a312c[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@58e6d4b8[Wrapped task = com.amazonaws.athena.connector.lambda.data.S3BlockSpiller$$Lambda$146/0x0000000840362c40@1de5f0ef]] 
rejected from …
```

adding RejectedExecutionHandler to blockspiller threadpool

---

athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchMetadataHandler.java

adding pagination for ListTables within the CW connector.

adding support for pagination within the Cloudwatch Connector

---

athena-mysql/athena-mysql.yaml
athena-postgresql/athena-postgresql.yaml
athena-redshift/athena-redshift.yaml

Fix versions in CFN

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcMetadataHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcRecordHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java
athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtilTest.java

Fixing superclass so that subclasses can properly use metrics.

Fix JDBC Metrics to include sourceType

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-elasticsearch/athena-elasticsearch.yaml
athena-example/athena-example.yaml
athena-federation-integ-test/README.md
athena-federation-sdk/athena-federation-sdk.yaml
athena-hbase/athena-hbase.yaml
athena-mysql/athena-mysql.yaml
athena-neptune/athena-neptune.yaml
athena-postgresql/athena-postgresql.yaml
athena-redis/athena-redis.yaml
athena-redshift/athena-redshift.yaml
athena-timestream/athena-timestream.yaml
athena-tpcds/athena-tpcds.yaml
athena-udfs/athena-udfs.yaml
athena-vertica/athena-vertica.yaml
pom.xml

Cut release 2022.10.1

---

athena-snowflake/README.md

*Issue #, if available:* #691
*Description of changes:* Fixing snowflake emoji in readme connstrs

Fixing snowflake emoji in readme connstrs

---

athena-hbase/src/main/java/com/amazonaws/athena/connectors/hbase/HbaseRecordHandler.java

The HBaseRecordHandler assumes that all predicates are over columns that
belong to a family. The primary key in HBase, row, has no family, and
this assumption leads to an exception when attempting to run a query
such as `SELECT * FROM "lambda:hbase"."default"."table" WHERE row =
<val>`. This change imports the `RowFilter` HBase class and uses this class instead of `SingleColumnValueFilter` when the predicate is over the primary key in order to fix this.
Prior to this change, I can run the following query:
```
select * from "lambda:hbase"."default"."hbase-store-sales" where row = '"14016-43534"'
```
and receive the error:
```
GENERIC_USER_ERROR: Encountered an exception[java.lang.ArrayIndexOutOfBoundsException] from your …
```

Bug Fix: Predicate over primary key error

---

athena-cloudera-hive/src/main/resources/log4j2.xml
athena-cloudera-impala/src/main/resources/log4j2.xml
athena-datalakegen2/src/main/resources/log4j2.xml
athena-google-bigquery/src/main/resources/log4j2.xml
athena-hortonworks-hive/src/main/resources/log4j2.xml
athena-oracle/src/main/resources/log4j2.xml
athena-saphana/src/main/resources/log4j2.xml
athena-snowflake/src/main/resources/log4j2.xml
athena-sqlserver/src/main/resources/log4j2.xml
athena-synapse/src/main/resources/log4j2.xml
athena-teradata/src/main/resources/log4j2.xml

*Issue # INC00001065, Connector Lambda Debug Log Level Messages Are Not Showing Up.*
*updated loggers as required for all ten connectors*

Fix for showing up debug level log messages

---

athena-google-bigquery/athena-google-bigquery.yaml

Removed BigQuery IAM role parameter and modified the policies in template file.

BigQuery IAM  role & policies changes in template file

---

athena-mysql/src/main/resources/log4j2.xml
athena-postgresql/src/main/resources/log4j2.xml
athena-redshift/src/main/resources/log4j2.xml

This change fixes some of the other log4j config files that were still wrong.

Fix the rest of the log4j configs

---

athena-cloudera-hive/etc/test-config.json
athena-cloudera-impala/etc/test-config.json
athena-cloudwatch/etc/test-config.json
athena-datalakegen2/etc/test-config.json
athena-docdb/etc/test-config.json
athena-dynamodb/etc/test-config.json
athena-elasticsearch/etc/test-config.json
athena-federation-integ-test/src/main/java/com/amazonaws/athena/connector/integ/IntegrationTestBase.java
athena-google-bigquery/etc/test-config.json
athena-hbase/etc/test-config.json
athena-hortonworks-hive/etc/test-config.json
athena-mysql/etc/test-config.json
athena-oracle/etc/test-config.json
athena-postgresql/etc/test-config.json
athena-redis/etc/test-config.json
athena-redshift/etc/test-config.json
athena-saphana/etc/test-config.json
athena-snowflake/etc/test-config.json
athena-sqlserver/etc/test-config.json
athena-synapse/etc/test-config.json
athena-teradata/etc/test-config.json
athena-timestream/etc/test-config.json
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TimestreamClientBuilderTest.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/integ/TimestreamIntegTest.java
tools/config_json_validator.py

- Integ Test Config File Fixes
- Add helper python script to validate json content of test config files
- timestream fixes for integ tests
735

Resolve Misc Issues in Integration Tests Package

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/TestBase.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/GlueMetadataHandler.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java

GlueFieldLexer, BlockUtils, DDB changes for map type support

---

athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexerTest.java

Disable map support for now

---

athena-oracle/README.md

Update athena-oracle/README.md with more details on ssl support for RDS

---

athena-federation-sdk/pom.xml
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/RecordBatchSerDe.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/SchemaSerDe.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/serde/v2/ArrowRecordBatchSerDe.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/serde/v2/BlockSerDe.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/serde/v2/SchemaSerDe.java
athena-jdbc/pom.xml
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcArrowTypeConverter.java
athena-neptune/pom.xml
athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataMetadataHandler.java
pom.xml

Includes upgrades to jackson and netty as well (required for the arrow upgrade).

Upgrade apache arrow version to 9.0.0

---

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandler.java

This is needed when users have mixed casing in their table names.
Issue #463
MongoDB collection with mixed casing:
Glue table settings:
Athena query:

athena-docdb: Make use of the Glue table property "sourceTable"

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java

Checks were removed with a prior change that should have still been there.
Added tests to prevent regressions again in the future.

DDBPredicateUtils: Fix bug with predicate generation

---

pom.xml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42004
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28491

Update fasterxml jackson to fix CVEs

---

athena-google-bigquery/athena-google-bigquery.yaml
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryConstants.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryUtils.java

*Description of changes:
Added Support for Private Endpoint in Google BigQuery Connector

Added Support for Private Endpoint in BigQuery Connector

---

athena-cloudwatch/athena-cloudwatch.yaml
athena-msk/athena-msk.yaml
athena-synapse/athena-synapse.yaml

Again, thanks to @adithyapathipaka for initially finding and fixing this in the DDB yaml.

Fix other yaml bugs when LambdaRole is provided

---

tools/bump_versions/bump_connectors_version.py
tools/bump_versions/bump_sdk_version.py
tools/bump_versions/common.py

tools/bump_versions: update logic to look at existing tags from git

---

athena-msk/pom.xml

athena-msk: Fix logging dependencies

---

athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandler.java
athena-saphana/src/test/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandlerTest.java

BigInt,SmallInt,TinyInt are converting into varchar.
Converted datatypes into appropriate arrow dataypes

fix datatype issues in saphana connector

---

athena-msk/athena-msk.yaml

athena-msk.yaml: Remove obsolete reference to GlueRegistryArn

---

tools/bump_versions/common.py

Prior to this patch the user is prompted by the `git fetch ...` command for a password if their ssh keys are password protected.
By leveraging the github api instead, we can avoid this entirely.

bump_versions/common.py: grab latest release tag from github api

---

athena-cloudwatch/src/main/java/com/amazonaws/athena/connectors/cloudwatch/CloudwatchMetadataHandler.java

athena-cloudwatch: Fix CloudwatchMetadataHandler returning multiple all_log_streams

---

.github/dependabot.yml

dependabot.yml: Increase open-pull-requests-limit for maven packages

---

athena-msk/athena-msk.yaml

athena-msk: simplify the sam template

---

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/TypeUtils.java

Added a case that handles BigInt data type and coerces value received from MongoDB client to proper type.

Added support for BigInt in DocDB connector

---

athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsMetadataHandler.java
athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsRecordHandler.java
athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/GcsUtil.java
athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/common/PartitionUtil.java
athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadata.java
athena-gcs/src/test/java/com/amazonaws/athena/connectors/gcs/common/PartitionUtilTest.java
athena-gcs/src/test/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadataTest.java

- Simplified the logic in checkPartitionWithConstraints/partitionConstraintsSatisfied to make it easier to reason about.
- Various other simplifications and cleanups.

athena-gcs: some more cleanup

---

athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandler.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TestUtils.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandlerTest.java

Fix issue #768 , Timestream connector return incorrect result for DATEMILLI field
Timestream connector return incorrect result for DATEMILLI field

Fix Timestream timestamp field value.

---

athena-gcs/src/main/java/com/amazonaws/athena/connectors/gcs/storage/StorageMetadata.java

In StorageMetadata.java:172 prior to this patch, it was trying to trim the leading / even when it didn't exist.
This patch fixes that and also fixes all other places in the athena-gcs connector where it tries to trim leading slashes using the error prone `.substring(1)` method.

athena-gcs: fix bug with trimming leading /

---

athena-aws-cmdb/athena-aws-cmdb.yaml
athena-cloudera-hive/athena-cloudera-hive.yaml
athena-cloudera-impala/athena-cloudera-impala.yaml
athena-cloudwatch-metrics/athena-cloudwatch-metrics.yaml
athena-cloudwatch/athena-cloudwatch.yaml
athena-datalakegen2/athena-datalakegen2.yaml
athena-db2/athena-db2.yaml
athena-docdb/athena-docdb.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-elasticsearch/athena-elasticsearch.yaml
athena-example/athena-example.yaml
athena-federation-sdk/athena-federation-sdk.yaml
athena-google-bigquery/athena-google-bigquery.yaml
athena-hbase/athena-hbase.yaml
athena-hortonworks-hive/athena-hortonworks-hive.yaml
athena-msk/athena-msk.yaml
athena-mysql/athena-mysql.yaml
athena-neptune/athena-neptune.yaml
athena-oracle/athena-oracle.yaml
athena-postgresql/athena-postgresql.yaml
athena-redis/athena-redis.yaml
athena-redshift/athena-redshift.yaml
athena-saphana/athena-saphana.yaml
athena-snowflake/athena-snowflake.yaml
athena-sqlserver/athena-sqlserver.yaml
athena-synapse/athena-synapse.yaml
athena-teradata/athena-teradata.yaml
athena-timestream/athena-timestream.yaml
athena-tpcds/athena-tpcds.yaml
athena-vertica/athena-vertica.yaml

improve description of the parameter in yaml file when creating connector

improve description of the parameter in yaml file

---

athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskConstants.java
athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskMetadataHandler.java
athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskRecordHandler.java

athena-msk: Update source type

---

athena-kafka/athena-kafka.yaml
athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaUtils.java

feature/athena-kafka:added support for scram without SSL encryption 

---

.github/workflows/maven_push.yml

Target java 8 to ensure source compatibility during pull requests.

.github/workflows/maven_push.yml: target java 8 to ensure source compatibility

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockAllocatorImpl.java

arrow states in their documentation that there is supposed to be only one RootAllocator per application.
So this is necessary because applications that use arrow beyond just for the Athena Federation SDK will already have their own RootAllocator.

Enhance BlockAllocatorImpl to take in a shared RootAllocator

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/domain/predicate/SortedRangeSet.java

These are useful functions that don't look like they were meant to be protected.

Some of the SortedRangeSet static utility functions public

---

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchDomainMapProvider.java

[1047](https://github.com/awslabs/aws-athena-query-federation/issues/1047)
getEndpoint() returns null if domain is in a VPC. Need to use getEndpoints() instead, which returns a Map containing key "vpc" that stores value of domain endpoint. This resolves issue of accessing and listing Tables of a domain located inside a VPC when `auto_discover_endpoint` is set to true and connector does not use `domain_mapping` environment variable.

Fixed accessing domain endpoints that are in a VPC when using auto_discover_endpoint

---

athena-kafka/src/main/java/com/amazonaws/athena/connectors/kafka/KafkaRecordHandler.java

Fix typo in Kafka connector

---

.github/workflows/cut_release.yml
.github/workflows/publish_to_maven_central.yml

Add github workflow to cut a release
Additionally renames the publish_to_maven_central.yml workflow to be more descriptive.

Add github workflow to cut a release

---

.github/workflows/cut_release.yml
.github/workflows/javadoc_sync.yaml
.github/workflows/maven_push.yml

workflows: Remove self-hosted runners
workflows/cut_release: fix change log issue
Need the entire history in order to properly generate the change log

Workflows updates

---

.github/workflows/codeql-analysis.yml
.github/workflows/cut_release.yml
.github/workflows/javadoc_sync.yaml
.github/workflows/maven_push.yml

workflows: use aws-athena-query-federation group

workflows: use aws-athena-query-federation group

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java
athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/TestBase.java
athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandlerTest.java

Fixes parsing Money Type in Postgres.
Issue #941

Added Money type support for Postgres Connector

---

.github/workflows/publish_to_maven_central.yml

publish_to_maven_central: add athena-federation-integ-test

publish_to_maven_central: add athena-federation-integ-test

---

athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtilTest.java

Add the tests that were mentioned by @ahggns but instead of doing a direct assertEquals on the ZonedDateTime perform the assertEquals on the underlying Instant and ZoneOffset to validate equality.
Issue #293

DateTimeFormatterUtilTest: verify round trip packing unpacking

---

athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandler.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryRecordHandler.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryUtils.java
athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandlerTest.java
athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryRecordHandlerTest.java

[fix]athena-google-bigquery: return athena catalog name instead of project name from gbq.

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java

return empty schema in ddb kms encrypted table when lambda role doesn't have access to KMS key.

return empty schema in ddb kms encrypted table when lacking kms permissions

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/SerDeVersion.java

Tested with a v2 and a v3 workgroup.

Drop SerDe version to 2 for connectors until Athena Engine V2 receives resolution fix

---

athena-cloudera-hive/src/main/java/com/amazonaws/athena/connectors/cloudera/HiveMetadataHandler.java

update show table query in cloudera hive

---

tools/publish.sh

Add back publish.sh script in case customers are using it

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/security/LocalKeyFactory.java

When we are using SecureRandom.getInstanceStrong(), it may block forever when reading from /dev/random on some platforms where it doesn't have enough entropy.
In those situations, instead of blocking forever, we will timeout now after 1 second and throw an exception.
Note that this might still happen even if we just use `new SecureRandom()` because it may read from /dev/random initially for as the `seedFile` before it switches to using /dev/urandom.
See: https://github.com/openjdk/jdk/blob/master/src/java.base/unix/classes/sun/security/provider/NativePRNG.java#L157

LocalKeyFactory: Don't block forever

---

athena-hortonworks-hive/src/main/java/com/amazonaws/athena/connectors/hortonworks/HiveMetadataHandler.java

make hortonworks hive compatible with java 8

---

athena-db2-as400/LICENSE.txt
athena-db2-as400/README.md
athena-db2-as400/athena-db2-as400.yaml
athena-db2-as400/etc/test-config.json
athena-db2-as400/pom.xml
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400CompositeHandler.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400Constants.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400MetadataHandler.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400MuxCompositeHandler.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400MuxMetadataHandler.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400MuxRecordHandler.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400QueryStringBuilder.java
athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400RecordHandler.java
athena-db2-as400/src/main/resources/log4j2.xml
athena-db2-as400/src/test/java/com/amazonaws/athena/connectors/db2as400/Db2As400CompositeHandlerTest.java
athena-db2-as400/src/test/java/com/amazonaws/athena/connectors/db2as400/Db2As400MetadataHandlerTest.java
athena-db2-as400/src/test/java/com/amazonaws/athena/connectors/db2as400/Db2As400QueryStringBuilderTest.java
athena-db2-as400/src/test/java/com/amazonaws/athena/connectors/db2as400/Db2As400RecordHandlerTest.java
athena-db2-as400/src/test/java/com/amazonaws/athena/connectors/db2as400/integ/Db2As400IntegTest.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/DatabaseConnectionConfigBuilder.java
pom.xml

This connector enables Amazon Athena to access your DB2 on iSeries (AS400) databases.

Amazon Athena DB2AS400 Connector

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/SerDeVersion.java

Bump serde to v4 for pushdown enhancement release

---

.github/workflows/run_release_tests.yml
.gitignore
validation_testing/Dockerfile
validation_testing/README.md
validation_testing/build.sh
validation_testing/cdk_federation_infra_provisioning/app/README.md
validation_testing/cdk_federation_infra_provisioning/app/cdk.json
validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/dynamodb.py
validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/mysql.py
validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/opensearch.py
validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/postgresql.py
validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/redshift.py
validation_testing/cdk_federation_infra_provisioning/app/lib/app.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/dynamo-stack.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/opensearch-stack.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/stack-props.ts
validation_testing/cdk_federation_infra_provisioning/app/package.json
validation_testing/cdk_federation_infra_provisioning/app/resources/tpcds_specs.json
validation_testing/cdk_federation_infra_provisioning/app/tsconfig.json
validation_testing/main.py
validation_testing/run_release_tests.sh
validation_testing/scripts/exec_release_test_queries.py
validation_testing/scripts/glue_job_synchronous_execution.py

- Contains CDK package for infra spinup, ETL, teardown
- Contains automated test workflow to ensure APIs can be hit without issue and pushdowns work
- Right now, we test just ddb and mysql
- Create GitHub workflow

Federation Release Tests Support

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java
athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandlerTest.java

Enable jdbc connector to return MATERIALIZED VIEW.

Enable jdbc to return MATERIALIZED VIEW.

---

athena-arrow-java-dist/arrow-dataset-10.0.1.pom
athena-arrow-java-dist/pom.xml
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandlerTest.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtil.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtilTest.java
pom.xml

Reverts awslabs/aws-athena-query-federation#1447

Revert "Use Arrow 13"

---

athena-federation-integ-test/pom.xml
athena-federation-sdk/pom.xml
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java
athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlQueryStringBuilderTest.java

Fix dynamic filter date on timezone issue.

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/domain/predicate/functions/StandardFunctions.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryFederationExpressionParser.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcFederationExpressionParser.java
athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlFederationExpressionParserTest.java
athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandlerTest.java

Temporary disable and/or complex expression for JDBC sources 

temporary disable and/or complex expression

---

athena-cloudera-hive/src/test/java/com/amazonaws/athena/connectors/cloudera/HiveRecordHandlerTest.java
athena-cloudera-impala/src/test/java/com/amazonaws/athena/connectors/cloudera/ImpalaRecordHandlerTest.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/domain/predicate/functions/StandardFunctions.java
athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockUtilsTest.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryFederationExpressionParser.java
athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryFederationExpressionParserTest.java
athena-hortonworks-hive/src/test/java/com/amazonaws/athena/connectors/hortonworks/HiveRecordHandlerTest.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/FederationExpressionParser.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcFederationExpressionParser.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/TypeAndValue.java
athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlFederationExpressionParserTest.java
athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlQueryStringBuilderTest.java
athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostgreSqlFederationExpressionParser.java
athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandlerTest.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaQueryStringBuilder.java

predicate pushdown fix on complex expression

---

.github/workflows/cut_release.yml

Adding `git status` to workflow, for a more detailed logs.

Debug release workflow

---

athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryFederationExpressionParserTest.java

add license header for BigQueryFederationExpressionParserTest

---

.github/workflows/maven_push.yml

Adding a step to `maven_push` workflow that will check if files have been modified as a result of running maven build.

Modified maven_push workflow

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java

checkstyle error when building locally. this fixes it

Fix checkstyle error in JDBCUtil

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/model/DynamoDBPaginatedTables.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBTableResolver.java
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandlerTest.java

Implement dynamodb pagination 

Implement dynamodb pagination

---

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchMetadataHandler.java

Implement elasticsearch pagination

---

athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java
athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandler.java

This change will allow Redshift Connector to support Redshift External Tables. 

Support Redshift External Schemas & Tables

---

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBCaseInsensitiveResolver.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandler.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/SchemaUtils.java
athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandlerTest.java
athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/SchemaUtilsTest.java

Enable case insensitive match for docdb on schema and table names

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java

Ignore IN Condition if it appears in KeyConditionExpression

---

athena-snowflake/assembly.xml

Currently the zip file is bringing in too much duplicate dependency with it. This should slim it down.

Snowflake assembly fix

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcArrowTypeConverter.java

fix for numeric data type having negative scale

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/glue/GlueFieldLexer.java

Disable map support

---

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeConstants.java

Inaccurate results with connector snowflake when data scanned exceeds threshold in aggregate functions 
Quick fix to create single split

single split for snowflake

---

.github/workflows/auto-approve.yml

Disabled Automerge DependBot PRs Temporarily

---

pom.xml

Maven dependency revert

---

athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2DataType.java
athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandler.java

Add data type conversion for athena-datalakegen2 QPT

---

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerDataType.java
athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java

Add data type conversion for athena-sqlserver QPT

---

athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandler.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryRecordHandler.java
athena-google-bigquery/src/main/java/com/amazonaws/athena/connectors/google/bigquery/qpt/BigQueryQueryPassthrough.java

Extended QPT to athena-bigquery

---

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandler.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandler.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/QueryUtils.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/qpt/DocDBQueryPassthrough.java

Extended QPT to athena-docdb

---

athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java
athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandler.java
athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftMetadataHandler.java

Will allow customers to execute QPT on Postgresql and Redshift

Extend QPT to Postgresql & Redshift

---

athena-dynamodb/athena-dynamodb.yaml
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/qpt/DDBQueryPassthrough.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/optimizations/querypassthrough/QueryPassthroughSignature.java

Will allow customer to execute QPT on DynamoDB using PartiQL; Only SELECT statements are supported.

Extended QPT to athena-dynamodb

---

athena-cloudera-impala/src/main/java/com/amazonaws/athena/connectors/cloudera/ImpalaMetadataHandler.java
athena-cloudera-impala/src/main/java/com/amazonaws/athena/connectors/cloudera/ImpalaRecordHandler.java

Will allow customer to execute QPT on Cloudera Impala

Extended QPT to athena-Impala

---

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java
athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeRecordHandler.java

Will allow customer to execute QPT on top of snowflake

Extended QPT to athena-snowflake

---

athena-hortonworks-hive/src/main/java/com/amazonaws/athena/connectors/hortonworks/HiveMetadataHandler.java
athena-hortonworks-hive/src/main/java/com/amazonaws/athena/connectors/hortonworks/HiveRecordHandler.java

Will allow customer to execute QPT on top of athena-hortonworks-hive

Extended QPT to athena-hortonworks-hive

---

athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataMetadataHandler.java
athena-teradata/src/main/java/com/amazonaws/athena/connectors/teradata/TeradataRecordHandler.java

Will allow customer to execute QPT on top of teradata

Extended QPT to athena-teradata

---

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java
athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleRecordHandler.java

Will allow customer to execute QPT on top of athena-oracle

Extended QPT to athena-oracle

---

athena-db2/src/main/java/com/amazonaws/athena/connectors/db2/Db2MetadataHandler.java
athena-db2/src/main/java/com/amazonaws/athena/connectors/db2/Db2RecordHandler.java

Will allow customer to execute QPT on top of db2

Extended QPT to athena-db2

---

athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2DataType.java
athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2MetadataHandler.java
athena-datalakegen2/src/main/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2RecordHandler.java
athena-datalakegen2/src/test/java/com/amazonaws/athena/connectors/datalakegen2/DataLakeGen2DataTypeTest.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java

Will allow customer to execute QPT on top of Datalakegen2

Extended QPT To Datalakegen2

---

athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerDataType.java
athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java
athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerRecordHandler.java

Will allow customer to execute QPT on top of sqlserver

Extended QPT to athena-sqlserver

---

athena-hbase/pom.xml

Hbase reduce jar size

---

athena-google-bigquery/pom.xml

This reverts commit 870b094dcc05426102723a7eb07cba61382daf22.

Revert "build(deps): bump com.google.cloud:google-cloud-bigquery"

---

athena-google-bigquery/pom.xml
athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandlerTest.java

com.google.cloud google cloud bigquery version update to 2.40.1
resolved build failed issue by correcting test case.

Com.google.cloud google cloud bigquery version update

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/CompositeHandler.java
athena-google-bigquery/pom.xml
athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryMetadataHandlerTest.java

Bigquery snowflake debug

---

.github/workflows/stalled.yml

fixes formatting issues in #1981 

Fixed GH Action Format Issue

---

athena-oracle/athena-oracle.yaml

the oracle connector to allow for custom role to be used.

custom role implementation in athena-oracle connector

---

athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/Constants.java
athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/NeptuneMetadataHandler.java

Enhance exception handling and logging error message for Neptune QPT. Currently Neptune PropertyGraph QPT will support gremlin query type as valueMap for other types will throw exception.

Enhance exception handling and logging error message for Neptune QPT

---

athena-hbase/pom.xml

unused dependency remove hbase connector and tested.

unused dependency remove hbase connector

---

athena-google-bigquery/pom.xml
athena-google-bigquery/src/test/java/com/amazonaws/athena/connectors/google/bigquery/BigQueryFederationExpressionParserTest.java

unused dependency removed from bigquery connector and tested.

unused dependency remove bigquery connector

---

.github/workflows/run_release_tests.yml

Metadata from the upstream server seems to be out of date; and needs most likely update before installing dependencies.

Updated before installing Dependencies

---

.github/dependabot.yml
athena-google-bigquery/pom.xml

Ignore BigQuery dependabot. Fix BigQueryVersion

---

athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/propertygraph/rowwriters/CustomSchemaRowWriter.java
athena-neptune/src/main/java/com/amazonaws/athena/connectors/neptune/propertygraph/rowwriters/VertexRowWriter.java

#1973 Handling array values in Neptune node
updated to consider array of values where only single value is set. Attached screen shot of array of value as ; separated.

Handling array values in Neptune node

---

athena-msk/pom.xml

Remove duplicate dependencies from athena-msk pom.xml

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/optimizations/DataSourceOptimizations.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/optimizations/pushdown/HintsSubtype.java

Allows engine to be aware of list of configurations through hints; specifically starting with Collation configuration. 
* Introduced new Hint pushdown subtype

Added Data Source Hints

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/security/AesGcmBlockCrypto.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/security/KmsKeyFactory.java

update KMS to AES_256

---

.github/dependabot.yml

ignore `aws-msk-iam-auth` for dependabot

---

athena-msk/pom.xml

Reverts awslabs/aws-athena-query-federation#2167
Breaks AWS MSK connector

Revert "build(deps): bump software.amazon.msk:aws-msk-iam-auth from 2.1.1 to 2.2.0"

---

athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/GlueRegistryReader.java

Fix return statement in getGlueSchemaType method

---

athena-msk/pom.xml

update v2-master with msk dependency change

---

athena-clickhouse/pom.xml
athena-cloudwatch/pom.xml
athena-elasticsearch/pom.xml
athena-federation-integ-test/pom.xml
athena-federation-sdk/pom.xml
athena-jdbc/pom.xml
athena-neptune/pom.xml
athena-redis/pom.xml
athena-snowflake/pom.xml
athena-synapse/pom.xml
pom.xml

V2 merge jsii

---

athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlQueryStringBuilder.java

Just updating the comment to highlight the exact condition for the Collate Aware query builder.

Updated Postgresql Split Query Comment

---

athena-elasticsearch/pom.xml
athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsElasticsearchFactory.java
athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchDomainMapProvider.java
athena-elasticsearch/src/test/java/com/amazonaws/athena/connectors/elasticsearch/ElasticsearchDomainMapProviderTest.java

Migrate Elasticsearch to AWS SDK v2.

v2 migration elasticsearch

---

athena-elasticsearch/pom.xml
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java
athena-msk/pom.xml
athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlQueryStringBuilder.java
athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandler.java
athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandlerTest.java
athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandler.java
athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandlerTest.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaQueryStringBuilder.java
pom.xml

V2 master merge 9/10

---

tools/bump_versions/bump_connectors_version.py
tools/bump_versions/common.py

Update the tools used to correct the semantic version to set the semantic version used in the ImageUri and Dockerfile

update new uses of semantic version

---

athena-timestream/pom.xml
athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamClientBuilder.java
athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamMetadataHandler.java
athena-timestream/src/main/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandler.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TestUtils.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TimestreamClientBuilderTest.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TimestreamMetadataHandlerTest.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/TimestreamRecordHandlerTest.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/integ/TimestreamIntegTest.java
athena-timestream/src/test/java/com/amazonaws/athena/connectors/timestream/integ/TimestreamWriteRecordRequestBuilder.java

timestreamwrite and timestreamquery update to v2 

v2 changes for timestream

---

athena-aws-cmdb/pom.xml
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/TableProviderFactory.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/EmrClusterTableProvider.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/TableProviderFactoryTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/EmrClusterTableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/RdsTableProviderTest.java
athena-hbase/pom.xml
athena-hbase/src/test/java/com/amazonaws/athena/connectors/hbase/integ/HbaseIntegTest.java

#2086 SDK v2 changes for EMR service
SDK v2 changes for EMR service

v2 sdk changes emr

---

athena-federation-integ-test/pom.xml
athena-federation-integ-test/src/main/java/com/amazonaws/athena/connector/integ/clients/CloudFormationClient.java

https://github.com/awslabs/aws-athena-query-federation/issues/2092
Update the use of Cloudformation in the integ test package.

v2 Cloudformation

---

.github/dependabot.yml
athena-cloudwatch/pom.xml
athena-db2-as400/athena-db2-as400.yaml
athena-db2/athena-db2.yaml
athena-dynamodb/athena-dynamodb.yaml
athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDbIntegTest.java
athena-elasticsearch/pom.xml
athena-federation-integ-test/pom.xml
athena-federation-sdk/pom.xml
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/exceptions/AthenaConnectorException.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/optimizations/DataSourceOptimizations.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/optimizations/pushdown/HintsSubtype.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/security/AesGcmBlockCrypto.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/security/KmsKeyFactory.java
athena-jdbc/pom.xml
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java
athena-kafka/pom.xml
athena-msk/pom.xml
athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlQueryStringBuilder.java
athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandler.java
athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlRecordHandlerTest.java
athena-redis/pom.xml
athena-redshift/src/main/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandler.java
athena-redshift/src/test/java/com/amazonaws/athena/connectors/redshift/RedshiftRecordHandlerTest.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaQueryStringBuilder.java
athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java
pom.xml

Merge in master 9/25

---

athena-aws-cmdb/pom.xml
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/TableProviderFactory.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/EbsTableProvider.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/Ec2TableProvider.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/ImagesTableProvider.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/RouteTableProvider.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/SecurityGroupsTableProvider.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/SubnetTableProvider.java
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/VpcTableProvider.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/TableProviderFactoryTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/EbsTableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/Ec2TableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/ImagesTableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/RouteTableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/SecurityGroupsTableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/SubnetTableProviderTest.java
athena-aws-cmdb/src/test/java/com/amazonaws/athena/connectors/aws/cmdb/tables/ec2/VpcTableProviderTest.java

SDK V2 ec2 changes

---

athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AWSRequestSigningApacheInterceptor.java
athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsRestHighLevelClient.java
athena-elasticsearch/src/main/java/com/amazonaws/athena/connectors/elasticsearch/AwsRestHighLevelClientFactory.java

v2 sdk changes elasticsearch AWSRequestSigningApacheInterceptor

v2 sdk changes elasticsearch AWSRequestSigningApacheInterceptor

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/qpt/DDBQueryPassthrough.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBTableResolver.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBPredicateUtils.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java
athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java

Error handling improvement changes for Athena Dynamo connector.

error handling changes for dynamodb

---

tools/bump_versions/common.py

The commands were edited before to work locally on MacOS. They are now changed back to work for unix.

fix commands to work for linux

---

athena-cloudera-hive/src/main/java/com/amazonaws/athena/connectors/cloudera/HiveQueryStringBuilder.java
athena-cloudera-hive/src/test/java/com/amazonaws/athena/connectors/cloudera/HiveRecordHandlerTest.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaQueryStringBuilder.java

#2326 
Overridden toPredicate method for Cloudera Hive to return casted Predicate for Timestamp.

Issue 2326 - Timestamp constraint in Cloudera Hive connector 

---

athena-postgresql/athena-postgresql-connection.yaml

ImageConfig got removed from the connections postgresql template, adding it back.

add ImageConfig back to postgres connection yaml

---

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeCaseInsensitiveResolver.java
athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java
athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeRecordHandler.java
athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java

Snowflake case insensitive match instead of upper case by default

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/connection/EnvironmentProperties.java

Check if auth is not null

---

athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java

address DDB Exception issue

---

athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBEnvironmentProperties.java
athena-docdb/src/test/java/com/amazonaws/athena/connectors/docdb/DocDBEnvironmentPropertiesTest.java

Fix docdb connection string

---

athena-tpcds/athena-tpcds-connection.yaml

glue connection reference fix

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/RdsSecretsCredentialProvider.java

Fix secret issue if field is integer

---

athena-docdb/Dockerfile
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBConnectionFactory.java

Adding RDS Certs To Docker Image

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/CompositeHandler.java

Changed message to debug

---

athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeCaseInsensitiveResolver.java
athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java
athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeRecordHandler.java
athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java

Fix hasUniquePrimaryKey query template casing issue. adding quote to the primary key as well as adding quote to table name

fix hasUniquePrimaryKey

---

.github/workflows/auto-approve.yml

Disabling Auto Approval Bot

---

athena-db2-as400/src/main/java/com/amazonaws/athena/connectors/db2as400/Db2As400EnvironmentProperties.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBMetadataHandler.java
athena-docdb/src/main/java/com/amazonaws/athena/connectors/docdb/DocDBRecordHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/JdbcEnvironmentProperties.java
athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java
athena-snowflake/src/test/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandlerTest.java

Little fixes to address some comments on larger PR

various cleanup fixes

---

athena-google-bigquery/athena-google-bigquery-connection.yaml
athena-google-bigquery/athena-google-bigquery.yaml

remove Trianz label

---

athena-redshift/pom.xml

Release tests fail due to a casing issue if this bump is done.
Example failure: https://github.com/awslabs/aws-athena-query-federation/actions/runs/12281442682/job/34270315939#step:9:1228
Succeeding with this branch: https://github.com/awslabs/aws-athena-query-federation/actions/runs/12285233052

revert bump

---

athena-jdbc/src/test/java/com/amazonaws/athena/connectors/jdbc/connection/GenericJdbcConnectionFactoryTest.java

Add SECRET_NAME_PATTERN unit test

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java

JDBCUtil Exception improvement

---

.github/workflows/maven_push.yml

Enable Code Coverage

---

.github/workflows/maven_push.yml

Added CodeCoverage Test Analyzer

---

athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleJdbcConnectionFactory.java

Added clearification comment regarding Oracle Cipher Suit

---

validation_testing/run_cleanup_infra.sh

We are not performing cleanup of ECR repos before attempting to deploy the new stack; this will ensure that.

Clean up ECR Repo per Connector if exits

---

.github/workflows/maven_push.yml
.github/workflows/publish_to_maven_central.yml

Two actions are currently using JDK8; even though all our release is happening using JDK11; 

Upgraded Github Action to JDK 11

---

athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/consumer/BaseMskConsumer.java
athena-msk/src/test/java/com/amazonaws/athena/connectors/msk/AmazonMskRecordHandlerTest.java

Msk connector was throwing null pointer exception when it encountered a completely null record. This change resolves that issue.
PFA testing doc for reference.
[MSK NullPointerException Issue Fix.docx](https://github.com/user-attachments/files/18782772/MSK.NullPointerException.Issue.Fix.docx)

Msk connector was throwing null pointer exception when entire record is null, issue fix.

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/connection/EnvironmentProperties.java

Allow custom endpoint to be used if required.

Allow custom glue endpoint to be used

---

.github/workflows/run_release_tests.yml

Code Coverage for the master branch is only updated on a Pull Request; this change will ensure that the Master branch stats is updated daily.

Update Code Cov on Daily Validation Tests

---

.github/workflows/run_release_tests.yml

yaml formatting error https://github.com/awslabs/aws-athena-query-federation/actions/runs/13340119230/workflow

Fix codecov format error

---

athena-aws-cmdb/athena-aws-cmdb-connection.yaml
athena-aws-cmdb/src/main/java/com/amazonaws/athena/connectors/aws/cmdb/tables/s3/S3BucketsTableProvider.java

Cmdb fix s3 permissions

---

athena-docdb/Dockerfile
athena-oracle/Dockerfile

fix openssl repo dependency issue.

---

athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandler.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaMuxMetadataHandler.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/resolver/SaphanaJDBCCaseResolver.java
athena-saphana/src/test/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandlerTest.java
athena-saphana/src/test/java/com/amazonaws/athena/connectors/saphana/resolver/SaphanaJDBCCaseResolverTest.java

Implemented case-insensitive search for saphana connector and check style issue fix.

Implemented case-insensitive search for saphana connector

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/credentials/DefaultCredentialsProvider.java
athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/credentials/StaticCredentialsProvider.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcMetadataHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/MultiplexingJdbcRecordHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/DatabaseConnectionConfigBuilder.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/connection/GenericJdbcConnectionFactory.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/DefaultJdbcFederationExpressionParser.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/FederationExpressionParser.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JDBCUtil.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcFederationExpressionParser.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcRecordHandler.java
athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcSplitQueryBuilder.java
athena-mysql/src/test/java/com/amazonaws/athena/connectors/mysql/MySqlFederationExpressionParserTest.java

Error handling improvement changes for Athena JDBC.

error handling changes for jdbc

---

validation_testing/cdk_federation_infra_provisioning/app/package.json
validation_testing/deploy_infra.sh

Release test fix

---

athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/serde/BaseDeserializer.java

Fix connector serde issue when client version mismatch.
Revert Error handling PR in BaseDeserializer

Fix connector serde issue when client version mismatch

---

athena-tpcds/src/main/java/com/amazonaws/athena/connectors/tpcds/mock/pagination/TPCDSMockMetadataHandler.java
athena-tpcds/src/test/java/com/amazonaws/athena/connectors/tpcds/mock/pagination/TPCDSMockMetadataHandlerTest.java

add mock TPCDSMockMetadataHandler for pagination testing

---

validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts

This reverts commit 897be459d7069b81003e00fdb1671c2b05fb57f4.

Revert "Upgrade Glue Job version to V4_0 (#2755)"

---

validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/postgresql_create_case_insensitive_data.py
validation_testing/cdk_federation_infra_provisioning/app/glue_scripts/redshift_create_case_insensitive_data.py
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/rds-generic-stack.ts
validation_testing/cdk_federation_infra_provisioning/app/lib/stacks/redshift-stack.ts

- Upgrade Glue Job version to V4_0

Upgrade Glue Job version to V4_0

---

athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandler.java
athena-saphana/src/main/java/com/amazonaws/athena/connectors/saphana/resolver/SaphanaJDBCCaseResolver.java
athena-saphana/src/test/java/com/amazonaws/athena/connectors/saphana/SaphanaMetadataHandlerTest.java

Saphana Connector pagination is not implemented.
Added pagination for saphana connector.

Added pagination for Saphana.

---

.github/workflows/maven_push.yml
.github/workflows/run_release_tests.yml

Reverting previous commit that broke the nightly tests; and fixing the order of the `slug` option 

Enable tests2

---

.github/workflows/code-guru-security.yml

Code guru security
